Repository CentaurusInfra/arktos, pull requests merged in 2020-11, with the labels that each got.

#798 fix iptables settings
  pkg/cloudgateway/cloudmesh/proxy/proxy.go
  pkg/edgegateway/edgemesh/proxy/proxy.go
Labels: approved, lgtm, size/S

#799 update ReleaseVirtualPresence function
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
Labels: approved, lgtm, size/XS

#796 update etcdimage from futurewei-cloud to centaurus-cloud
  cluster/common.sh
  cluster/images/etcd-empty-dir-cleanup/Makefile
  cluster/images/etcd/Makefile
  hack/lib/etcd.sh
Labels: approved, lgtm, size/S

#801 add scale-out env setup
  docs/setup-guide/scale-out-poc-setup.md
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  hack/lib/util.sh
Labels: approved, size/XL

#802 fixed issue with the setup
  cmd/kube-controller-manager/app/controllermanager.go
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
Labels: size/S

#780 Change fieldSelector value in APIServerConfigManager
  cmd/kube-proxy/app/BUILD
  cmd/kube-proxy/app/server.go
  cmd/kubelet/app/server.go
  staging/src/k8s.io/client-go/datapartition/BUILD
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
Labels: approved, lgtm, size/S

#804 automate proxy config in scale-out setup
  docs/setup-guide/scale-out-poc-setup.md
  hack/arktos-up-scale-out-poc.sh
  hack/scale_out_poc/nginx.conf
  hack/scale_out_poc/setup_nginx_proxy.sh
Labels: approved, lgtm, size/L

#809 fix scale-out setup script
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  hack/lib/util.sh
  hack/scale_out_poc/nginx.conf
Labels: size/M

#812 Make sure lease create/renew can use different api server
  pkg/kubelet/nodelease/BUILD
  pkg/kubelet/nodelease/controller.go
Labels: approved, lgtm, size/S

#810 nginx proxy setting with two TPs
  hack/scale_out_poc/two_TP/nginx.conf
  hack/scale_out_poc/two_TP/setup_nginx_proxy.sh
Labels: approved, lgtm, size/L

#813 Initial implemenation of ScaleOut architecture for kubemark in GCE
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/util.sh
  cluster/validate-cluster.sh
  docs/setup-guide/scale-out-poc-setup.md
  test/kubemark/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/XL

#811 Expand kubelet's clientset to support multiple tenant partitions
  cmd/kubelet/app/options/options.go
  cmd/kubelet/app/server.go
  cmd/kubemark/hollow-node.go
  hack/arktos-up-scale-out-poc.sh
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod_actions.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/volume_host.go
  pkg/kubemark/hollow_kubelet.go
Labels: approved, lgtm, size/L

#808 Minor changes to scale out poc setup manual.
  docs/setup-guide/scale-out-poc-setup.md
Labels: approved, lgtm, size/S

#815 Node Controller directly connecting to multi-TP
  api/api-rules/violation_exceptions.list
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/nodelifecyclecontroller.go
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/BUILD
  pkg/controller/nodelifecycle/config/types.go
  pkg/controller/nodelifecycle/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/nodelifecycle/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/scale_out_poc_util.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/util/node/controller_utils.go
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.conversion.go
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#819 use different update channel for multiple api server partitions
  pkg/kubelet/kubelet.go
Labels: approved, lgtm, size/XS

#818 pod status update using multiple kube clients
  pkg/kubelet/kubelet.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/status/status_manager.go
Labels: Verifying, approved, lgtm, size/M

#821 Updated mkdocs.yml
  mkdocs.yml
Labels: approved, lgtm, size/XS

#827 fix NodeNotReady issue
  cluster/gce/util.sh
  hack/scale_out_poc/nginx.conf
Labels: approved, lgtm, size/XS

#828 fix secret list and watch
  cmd/kubelet/app/server.go
  hack/scale_out_poc/two_TP/nginx.conf
  pkg/kubelet/kubelet.go
  pkg/kubelet/secret/secret_manager.go
Labels: approved, lgtm, size/M

#829 Drop service account param, tune up nginx params
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
Labels: approved, lgtm, size/S

#823 Kubemark hollow-node to support multiple tenant partitions
  cmd/kubemark/hollow-node.go
  test/kubemark/resources/hollow-node_template.yaml
  test/kubemark/start-kubemark.sh
Labels: Verifying, approved, lgtm, size/M

#830 add fallback to kubeclient 0 if only one is provided
  pkg/kubelet/kubelet.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/status/status_manager.go
Labels: approved, lgtm, size/XS

#831 Modify cluster verification to bypass proxy and directly talk to cluster apiserver
  cluster/gce/util.sh
  test/kubemark/gce/util.sh
Labels: approved, lgtm, size/S

#833 Cherry pick kubelet related changes to scale-out-poc-m1 branch + minor bug fix
  cluster/gce/util.sh
  cmd/kubelet/app/options/options.go
  cmd/kubelet/app/server.go
  cmd/kubemark/hollow-node.go
  hack/arktos-up-scale-out-poc.sh
  hack/scale_out_poc/two_TP/nginx.conf
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod_actions.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/volume_host.go
  pkg/kubemark/hollow_kubelet.go
  test/kubemark/gce/util.sh
  test/kubemark/resources/hollow-node_template.yaml
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/L

#832 1.18 improvement - reflector perf changes
  cmd/kubelet/app/server_bootstrap_test.go
  staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go
  staging/src/k8s.io/apimachinery/pkg/util/net/http.go
  staging/src/k8s.io/apimachinery/pkg/util/net/util.go
  staging/src/k8s.io/apimachinery/pkg/util/net/util_test.go
  staging/src/k8s.io/apimachinery/pkg/util/wait/BUILD
  staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
  staging/src/k8s.io/apimachinery/pkg/util/wait/wait_test.go
  staging/src/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  staging/src/k8s.io/apiserver/pkg/storage/tests/cacher_test.go
  staging/src/k8s.io/client-go/rest/request.go
  staging/src/k8s.io/client-go/tools/cache/BUILD
  staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
  staging/src/k8s.io/client-go/tools/cache/listwatch.go
  staging/src/k8s.io/client-go/tools/cache/reflector.go
  staging/src/k8s.io/client-go/tools/cache/reflector_metrics.go
  staging/src/k8s.io/client-go/tools/cache/reflector_test.go
  staging/src/k8s.io/client-go/tools/pager/pager.go
  staging/src/k8s.io/client-go/tools/pager/pager_test.go
  staging/src/k8s.io/client-go/tools/watch/retrywatcher.go
  test/cmd/request-timeout.sh
  test/integration/apimachinery/BUILD
  test/integration/apimachinery/watch_timeout_test.go
  test/integration/apiserver/apiserver_test.go
Labels: approved, lgtm, size/XXL

#825 Fix concurrent map write issue at AggregateWatcher stop
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
  staging/src/k8s.io/apimachinery/pkg/watch/watch_test.go
Labels: approved, lgtm, size/M
