Repository CentaurusInfra/arktos, pull requests merged in 2020-04, with the labels that each got.

#165 Bug fix for aggregated watch
  staging/src/k8s.io/client-go/tools/clientcmd/merged_client_builder.go
  staging/src/k8s.io/client-go/tools/clientcmd/merged_client_builder_test.go
Labels: area/scalability

#163 Update api server partitioning document + fix&refactor common scripts
  README.md
  docs/setup-guide/arktos-apiserver-partition.md
  docs/setup-guide/setup-dev-env.md
  hack/arktos-apiserver-partition.md
  hack/arktos-apiserver-partition.sh
  hack/arktos-up.sh
  hack/lib/common-var-init.sh
Labels: area/scalability

#164 fixed a few issues for multi-tenancy access control
  pkg/registry/rbac/role/registry.go
  pkg/registry/rbac/validation/rule.go
  pkg/registry/rbac/validation/rule_test.go
  plugin/pkg/auth/authorizer/rbac/BUILD
  plugin/pkg/auth/authorizer/rbac/rbac.go
  staging/src/k8s.io/client-go/listers/rbac/v1/role.go
Labels: area/multi-tenancy, bug

#172 Design doc for API Server Data Partition
  docs/design-proposals/apiserver/Data-Partition-Design.md
Labels: area/scalability, documentation

#160 Suppress extraneous updates of node status runtime readiness with no status change
  pkg/kubelet/nodestatus/setters.go
  pkg/kubelet/nodestatus/setters_test.go
Labels: area/node-agent, bug

#156 Add a documentation page for Arktos
  docs/slides/arktos_current_work_and_next.pdf
  docs/user-guide/Arktos-Release-Notes.md
  docs/user-guide/CONTRIBUTING.md
  docs/user-guide/README.md
  mkdocs.yml
  readthedocs.yaml
Labels: do-not-merge, documentation

#157 update authentication in multi-tenancy-access-control.md
  docs/design-proposals/multi-tenancy/multi-tenancy-access-control.md
Labels: area/multi-tenancy

#181 add tests with regular tenant or ruleResolver.RulesFor
  pkg/registry/rbac/validation/rule_test.go
Labels: area/multi-tenancy

#189 Arktos-up: conditional skip CA file generating + allow using master i…
  hack/lib/common-var-init.sh
  hack/lib/common.sh
Labels: area/scalability

#192 Allow api server instance from other service group to remove expired …
  pkg/master/reconcilers/lease.go
  pkg/master/reconcilers/lease_test.go
  pkg/master/reconcilers/mastercount.go
  pkg/registry/rbac/validation/BUILD
  pkg/registry/rbac/validation/rule_test.go
  test/integration/apiserver/apiserver_partition_test.go
  test/integration/master/kube_apiserver_test.go
Labels: area/scalability

#198 Remove redundent code in arktos-up.sh - generate_certs & start_apiserver
  hack/arktos-up.sh
Labels: code quality

#204 fix mistakenly reversed namespace and tenant in parameter
  plugin/pkg/auth/authorizer/rbac/rbac.go
Labels: bug

#203 Workload controller manager needs to die sooner #174
  cmd/workload-controller-manager/app/config/controllerconfig.go
  cmd/workload-controller-manager/app/controllermanager.go
  cmd/workload-controller-manager/config/controllerconfig.json
  pkg/cloudfabric-controller/deployment/deployment_controller.go
  pkg/cloudfabric-controller/replicaset/replica_set.go
  pkg/registry/core/controllerinstance/storage/storage.go
Labels: area/controller-manager

#202 Add README.md to docs folder for documentation home page
  docs/README.md
Labels: documentation

#208 Enable multi-tenancy in job controller
  pkg/controller/job/job_controller.go
  pkg/controller/job/job_controller_test.go
Labels: area/multi-tenancy

#215 fix cluster role getter in rbac for multitenancy
  pkg/registry/rbac/clusterrole/registry.go
  pkg/registry/rbac/validation/rule.go
  pkg/registry/rbac/validation/rule_test.go
  plugin/pkg/auth/authorizer/rbac/rbac.go
  plugin/pkg/auth/authorizer/rbac/rbac_test.go
  plugin/pkg/auth/authorizer/rbac/subject_locator_test.go
Labels: area/multi-tenancy

#201 Migrated etcd 3.3.10 to etcd 3.4.4 cluster server image changes
  build/dependencies.yaml
  build/workspace.bzl
  cluster/gce/config-test.sh
  cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd-empty-dir-cleanup/Makefile
  cluster/images/etcd/Makefile
  cluster/images/etcd/README.md
  cluster/images/etcd/migrate-if-needed.sh
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/constants/constants_test.go
  hack/lib/etcd.sh
  test/utils/image/manifest.go
Labels: area/scalability

#234 Unit test for APIServerConfigManager & updater
  docs/setup-guide/arktos-apiserver-partition.md
  staging/src/k8s.io/client-go/apiserverupdate/BUILD
  staging/src/k8s.io/client-go/apiserverupdate/update.go
  staging/src/k8s.io/client-go/apiserverupdate/update_test.go
  staging/src/k8s.io/client-go/datapartition/BUILD
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager_test.go
Labels: area/scalability

#239 API Server config connection failure tolerence in Kubelet - static pod start with out api server
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-proxy/app/server.go
  cmd/kube-scheduler/app/server.go
  cmd/kubelet/app/server.go
  cmd/workload-controller-manager/app/controllermanager.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
Labels: area/performance-test, area/scalability

#237 Find largest scope space and split it for new Controller Manager instance
  pkg/cloudfabric-controller/controllerframework/controller_framework.go
  pkg/cloudfabric-controller/controllerframework/controller_framework_test.go
Labels: area/controller-manager
