Repository CentaurusInfra/arktos, pull requests merged in 2020-10, with the labels that each got.

#771 update OWNERS file to work with bot
  OWNERS
Labels: size/M

#773 Replace panda with yxiong2020
  OWNERS
Labels: approved, lgtm, size/XS

#779 Add CHANGELOG for V0.6
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/README.md
Labels: approved, lgtm, size/S

#769 Add test cases for mizar node controller
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/grpc_adaptor.go
  pkg/controller/mizar/grpc_adaptor_mock.go
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-endpoints-controller.go
  pkg/controller/mizar/mizar-node-controller.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-service-controller.go
  pkg/controller/mizar/mizar_node_controller_test.go
  pkg/controller/mizar/testutil.go
  pkg/controller/mizar/util.go
  pkg/controller/mizar/util_test.go
Labels: approved, lgtm, size/XL

#770 Mux bug fix in ETCD store for partition
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager.go
Labels: approved, lgtm, size/M

#785 add new modules: cloudmesh and edgemesh
  cmd/cloudgateway/app/options/options.go
  cmd/cloudgateway/app/server.go
  cmd/edgegateway/app/options/options.go
  cmd/edgegateway/app/server.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/apis/edgegateway/v1/types.go
  pkg/cloudgateway/cloudhub/channelq/channelq.go
  pkg/cloudgateway/cloudmesh/cloudmesh.go
  pkg/cloudgateway/common/modules/group.go
  pkg/cloudgateway/common/modules/name.go
  pkg/edgegateway/common/modules/group.go
  pkg/edgegateway/common/modules/names.go
  pkg/edgegateway/edgemesh/edgemesh.go
Labels: approved, lgtm, size/L

#626 update design document for cloud-edge communication framework feature
  docs/design-proposals/cloud-edge-communication/Proposal-B1.png
  docs/design-proposals/cloud-edge-communication/Proposal-B2.png
  docs/design-proposals/cloud-edge-communication/Proposal-B3.png
  docs/design-proposals/cloud-edge-communication/Proposal-B4.png
  docs/design-proposals/cloud-edge-communication/Proposal-B5.png
  docs/design-proposals/cloud-edge-communication/cloud-edge-communication-framework.md
Labels: approved, lgtm, size/M

#786 add data plane message communication between cloud and edge site
  cmd/cloudgateway/app/options/options.go
  cmd/edgegateway/app/options/options.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/apis/edgegateway/v1/types.go
  pkg/cloudgateway/cloudmesh/cloudmesh.go
  pkg/cloudgateway/cloudmesh/config/config.go
  pkg/cloudgateway/cloudmesh/server/server.go
  pkg/cloudgateway/cloudmesh/taptun/taptun.go
  pkg/edgegateway/edgemesh/client/client.go
  pkg/edgegateway/edgemesh/config/config.go
  pkg/edgegateway/edgemesh/edgemesh.go
  pkg/edgegateway/edgemesh/process.go
  pkg/edgegateway/edgemesh/taptun/taptun.go
Labels: approved, lgtm, size/L

#782 Remove bcast from aggregated watcher. Use watcher stop to exit goroutine
  staging/src/k8s.io/apimachinery/pkg/watch/BUILD
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
  staging/src/k8s.io/apimachinery/pkg/watch/watch_test.go
Labels: approved, lgtm, size/L

#789 fix broken links
  README.md
Labels: approved, lgtm, size/S

#788 sync service expose information to cloudmesh
  pkg/cloudgateway/cloudmesh/cloudmesh.go
  pkg/cloudgateway/cloudmesh/proxy/proxy.go
  pkg/cloudgateway/common/constants/default.go
  pkg/cloudgateway/common/modules/group.go
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
  pkg/edgegateway/common/modules/group.go
  pkg/edgegateway/edgemesh/edgemesh.go
Labels: approved, lgtm, size/L

#794 delete related information after deleting exposed service
  pkg/cloudgateway/cloudmesh/proxy/proxy.go
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
  pkg/edgegateway/edgemesh/proxy/proxy.go
Labels: approved, lgtm, size/M

#795 get tap ip address in site information
  pkg/apis/cloudgateway/v1/types.go
  pkg/cloudgateway/cloudmesh/proxy/proxy.go
  pkg/cloudgateway/common/constants/default.go
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
  pkg/edgegateway/common/constants/default.go
  pkg/edgegateway/edgemesh/proxy/proxy.go
Labels: approved, lgtm, size/M

#791 etcd grpc proxy
  build/lib/release.sh
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/manifests/BUILD
  cluster/gce/manifests/etcd-grpc-proxy.manifest
  cluster/gce/util.sh
Labels: approved, lgtm, size/L

#797 update the usage of tap interface on the cloud
  cmd/cloudgateway/app/options/options.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/cloudgateway/cloudmesh/config/config.go
  pkg/cloudgateway/cloudmesh/proxy/proxy.go
  pkg/cloudgateway/cloudmesh/server/server.go
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
  pkg/edgegateway/edgemesh/client/client.go
  pkg/edgegateway/edgemesh/config/config.go
  pkg/edgegateway/edgemesh/proxy/proxy.go
Labels: approved, lgtm, size/L
