Repository CentaurusInfra/arktos, pull requests merged in 2020-09, with the labels that each got.

#651 bump up runtime version
  hack/lib/common-var-init.sh
  test/yaml/vm_default.yaml
  test/yaml/vm_with_persistedVolumes/vm_aws_static_pv.yaml
  test/yaml/vm_with_persistedVolumes/vm_datadisk_flexvol.yaml
  test/yaml/vm_with_persistedVolumes/vm_datadisk_pv.yaml
  test/yaml/vm_with_persistedVolumes/vm_rootfs_pv.yaml
Labels: size/S

#640 Fix API server config update "concurrent map iteration and map write" (bug 639)
  staging/src/k8s.io/client-go/apiserverupdate/BUILD
  staging/src/k8s.io/client-go/apiserverupdate/update.go
  staging/src/k8s.io/client-go/apiserverupdate/update_test.go
  staging/src/k8s.io/client-go/rest/config.go
Labels: bug, size/L

#630 Fix a thread safety issue in client.go
  staging/src/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/typed/cr/v1/cr_client.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/apiextensions_client.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/arktosextensions_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1/admissionregistration_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/apps_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/apps/v1beta1/apps_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/apps/v1beta2/apps_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1/auditregistration_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/authentication/v1/authentication_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/authentication/v1beta1/authentication_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/authorization/v1/authorization_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/authorization/v1beta1/authorization_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/autoscaling/v1/autoscaling_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1/autoscaling_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2/autoscaling_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/batch/v1/batch_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/batch/v1beta1/batch_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/batch/v2alpha1/batch_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/certificates/v1beta1/certificates_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/coordination/v1/coordination_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/coordination/v1beta1/coordination_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/core_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/events/v1beta1/events_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/extensions_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/networking/v1/networking_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/networking/v1beta1/networking_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/node/v1alpha1/node_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/node/v1beta1/node_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/policy/v1beta1/policy_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1/rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1/rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1beta1/rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/scheduling/v1/scheduling_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1/scheduling_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/scheduling/v1beta1/scheduling_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/settings/v1alpha1/settings_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/storage/v1/storage_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/storage/v1alpha1/storage_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/storage/v1beta1/storage_client.go
  staging/src/k8s.io/code-generator/_examples/MixedCase/clientset/versioned/typed/example/v1/example_client.go
  staging/src/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example/internalversion/example_client.go
  staging/src/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example2/internalversion/example2_client.go
  staging/src/k8s.io/code-generator/_examples/apiserver/clientset/versioned/typed/example/v1/example_client.go
  staging/src/k8s.io/code-generator/_examples/apiserver/clientset/versioned/typed/example2/v1/example2_client.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/example_client.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example2/v1/example2_client.go
  staging/src/k8s.io/code-generator/cmd/client-gen/generators/generator_for_group.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiregistration_client.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/internalclientset/typed/apiregistration/internalversion/apiregistration_client.go
  staging/src/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/metrics_client.go
  staging/src/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/metrics_client.go
  staging/src/k8s.io/node-api/pkg/client/clientset/versioned/typed/node/v1alpha1/node_client.go
  staging/src/k8s.io/sample-apiserver/pkg/generated/clientset/versioned/typed/wardle/v1alpha1/wardle_client.go
  staging/src/k8s.io/sample-apiserver/pkg/generated/clientset/versioned/typed/wardle/v1beta1/wardle_client.go
  staging/src/k8s.io/sample-controller/pkg/generated/clientset/versioned/typed/samplecontroller/v1alpha1/samplecontroller_client.go
Labels: size/L

#529 RBAC: kubelet reads network custom resource
  cluster/addons/rbac/kubelet-network-reader/kubelet-network-reader.yaml
  hack/arktos-up.sh
Labels: bug, size/S

#653 Fix concurrent map iteration and map write in AggregatedWatcher GetErrors (Issue 650)
  staging/src/k8s.io/apimachinery/pkg/watch/BUILD
  staging/src/k8s.io/apimachinery/pkg/watch/filter_test.go
  staging/src/k8s.io/apimachinery/pkg/watch/streamwatcher_test.go
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
  staging/src/k8s.io/apimachinery/pkg/watch/watch_test.go
Labels: bug, size/M

#664 fix bug 631/641
  pkg/kubectl/cmd/create/create_clusterrole.go
  pkg/kubectl/cmd/create/create_cronjob.go
  pkg/kubectl/cmd/create/create_role.go
  pkg/kubectl/describe/versioned/describe.go
Labels: size/S

#668 update setup_client.sh for e2e tests
  hack/setup-multi-tenancy/setup_client.sh
Labels: size/L

#449 kubelet prepares pod DNS config with network specific DNS service IP
  cmd/kubelet/app/BUILD
  cmd/kubelet/app/server.go
  pkg/kubelet/BUILD
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/network/dns/BUILD
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/network/dns/dns_test.go
Labels: size/L

#665 Bug fix for no change in WCM.
  pkg/cloudfabric-controller/controllerframework/controller_framework.go
Labels: size/XS

#672 add cloudgateway api definition
  pkg/apis/cloudgateway/register.go
  pkg/apis/cloudgateway/v1/doc.go
  pkg/apis/cloudgateway/v1/register.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/apis/cloudgateway/v1/zz_generated.deepcopy.go
Labels: size/L

#627 Update setup-dev-node script and fix an error
  hack/setup-dev-node.sh
Labels: size/XS

#674 Fix UT for unsorted enumeration.
  staging/src/k8s.io/client-go/rest/config_test.go
Labels: size/XS

#673 Multi tenancy/admission e2e tests
  test/e2e/arktos/multi_tenancy/run-e2e-test.sh
  test/e2e/arktos/multi_tenancy/test_suites/admission/test_cross_tenant.yaml
  test/e2e/arktos/multi_tenancy/test_suites/admission/test_tenant_exists.yaml
  test/e2e/arktos/multi_tenancy/testdata/sample-pod.yaml
Labels: size/L

#678 Bug fix for API Server Config Update Notification
  staging/src/k8s.io/client-go/apiserverupdate/update.go
  staging/src/k8s.io/client-go/apiserverupdate/update_test.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager_test.go
Labels: size/L

#681 export log when tests fail
  build/root/Makefile
Labels: size/XS

#686 hollow-node initializes arktos kube-client
  cmd/kubemark/BUILD
  cmd/kubemark/hollow-node.go
  pkg/kubemark/BUILD
  pkg/kubemark/hollow_kubelet.go
Labels: bug, size/S

#509 deploy DNS per network
  cmd/flat-network-controller/app/BUILD
  cmd/flat-network-controller/app/controller.go
  cmd/flat-network-controller/app/controller_test.go
  cmd/flat-network-controller/app/dns_deployment.go
  cmd/flat-network-controller/app/dns_deployment_test.go
  cmd/flat-network-controller/flat-network-controller.go
  pkg/controller/artifacts/coredns.yaml.in
Labels: area/multi-tenancy, size/XL

#675 kubelet starts pod after network is ready and dns service has IP assigned
  pkg/kubelet/network/dns/BUILD
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/network/dns/dns_test.go
Labels: area/networking, size/M

#689 validate cloudhub module and remove token
  cmd/cloudgateway/app/options/options.go
  cmd/cloudgateway/app/options/validation.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/cloudgateway/cloudhub/cloudhub.go
  pkg/cloudgateway/cloudhub/config/config.go
  pkg/cloudgateway/cloudhub/servers/httpserver/server.go
  pkg/cloudgateway/cloudhub/servers/httpserver/signcerts.go
  pkg/cloudgateway/common/constants/default.go
Labels: size/L

#690 add edgegateway
  cmd/edgegateway/app/options/options.go
  cmd/edgegateway/app/options/validation.go
  cmd/edgegateway/app/server.go
  cmd/edgegateway/edgegateway.go
  pkg/apis/edgegateway/register.go
  pkg/apis/edgegateway/v1/types.go
  pkg/edgegateway/common/constants/default.go
  pkg/edgegateway/common/modules/group.go
  pkg/edgegateway/common/modules/names.go
  pkg/edgegateway/edgehub/config/config.go
  pkg/edgegateway/edgehub/edgehub.go
Labels: size/L

#638 A simple end to end pod with vm type in E2E
  test/conformance/testdata/conformance.txt
  test/e2e/node/BUILD
  test/e2e/node/vmpods.go
  test/utils/image/manifest.go
Labels: size/L

#662 multi-tenancy CRD e2e tests
  test/e2e/arktos/multi_tenancy/run-e2e-test.sh
  test/e2e/arktos/multi_tenancy/test_suites/crd/test_per_tenant_crd.yaml
  test/e2e/arktos/multi_tenancy/test_suites/crd/test_system_share_crd.yaml
  test/e2e/arktos/multi_tenancy/testdata/forced_share_crd.yaml
  test/e2e/arktos/multi_tenancy/testdata/forced_share_crd_resource.yaml
  test/e2e/arktos/multi_tenancy/testdata/regular_crd.yaml
  test/e2e/arktos/multi_tenancy/testdata/regular_crd_resource.yaml
Labels: size/L

#677 update multi-tenancy controller/tenant-init e2e test cases
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_deployment_replicaset_controller.yaml
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_endpoints_controller.yaml
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_sa_token_controller.yaml
  test/e2e/arktos/multi_tenancy/test_suites/tenant_init_delete_test.yaml
Labels: size/L

#691 edgegateway connect to cloudgateway
  cmd/edgegateway/app/options/options.go
  cmd/edgegateway/app/server.go
  pkg/apis/edgegateway/v1/types.go
  pkg/edgegateway/edgehub/clients/adapter.go
  pkg/edgegateway/edgehub/clients/factory.go
  pkg/edgegateway/edgehub/clients/quicclient/quicclient.go
  pkg/edgegateway/edgehub/clients/wsclient/websocket.go
  pkg/edgegateway/edgehub/config/config.go
  pkg/edgegateway/edgehub/edgehub.go
  pkg/edgegateway/edgehub/process.go
Labels: size/L

#692 API server config read lock.
  staging/src/k8s.io/client-go/apiserverupdate/update.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager_test.go
Labels: size/S

#695 edgegateway gets certificates from cloudgatway
  cmd/edgegateway/app/options/options.go
  pkg/apis/edgegateway/v1/types.go
  pkg/cloudgateway/cloudhub/servers/httpserver/server.go
  pkg/cloudgateway/cloudhub/servers/httpserver/signcerts.go
  pkg/edgegateway/common/constants/default.go
  pkg/edgegateway/edgehub/certificate/certmanager.go
  pkg/edgegateway/edgehub/common/certutil/certfile.go
  pkg/edgegateway/edgehub/common/http/http.go
  pkg/edgegateway/edgehub/edgehub.go
Labels: size/L

#671 Add mizar-pod-controller and Grpc client
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/mizarcontrollers.go
  go.mod
  hack/testdata/mizar/mizar-grpc-configmap.yaml
  pkg/controller/BUILD
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/builtins.pb.go
  pkg/controller/mizar/builtins.proto
  pkg/controller/mizar/grpc-adaptor.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-starter-controller.go
  pkg/controller/mizar/util.go
Labels: size/XXL

#699 arktos network controller manages network object status phase
  cmd/arktos-network-controller/app/controller.go
  cmd/arktos-network-controller/app/controller_test.go
  cmd/arktos-network-controller/app/dns_deployment.go
  cmd/arktos-network-controller/app/dns_deployment_test.go
  cmd/arktos-network-controller/network-controller.go
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
Labels: size/L

#685 Fix 'updating kernel flag panic' issue in kubelet during perf tests
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
Labels: size/M

#700 create per-tenant-network kubernetes service
  cmd/arktos-network-controller/app/BUILD
  cmd/arktos-network-controller/app/controller.go
  cmd/arktos-network-controller/app/controller_test.go
  cmd/arktos-network-controller/app/wellknown_service.go
Labels: size/L

#707 adds feature gate MandatoryArktosNetwork to enforce network exists for each non-host pod
  hack/arktos-up.sh
  pkg/features/kube_features.go
  pkg/kubelet/network/dns/BUILD
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/network/dns/dns_test.go
Labels: size/M

#711 fix not import bugs in crd register
  pkg/apis/cloudgateway/v1/register.go
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
Labels: size/S

#713 delete no used auto generated code
  pkg/client/clientset/versioned/typed/cloudgateway/v1/epolicy.go
  pkg/client/clientset/versioned/typed/cloudgateway/v1/eserver.go
  pkg/client/clientset/versioned/typed/cloudgateway/v1/fake/fake_epolicy.go
  pkg/client/clientset/versioned/typed/cloudgateway/v1/fake/fake_eserver.go
  pkg/client/clientset/versioned/typed/cloudgateway/v1/fake/fake_virtualpresence.go
  pkg/client/clientset/versioned/typed/cloudgateway/v1/virtualpresence.go
  pkg/client/informers/externalversions/cloudgateway/v1/epolicy.go
  pkg/client/informers/externalversions/cloudgateway/v1/eserver.go
  pkg/client/informers/externalversions/cloudgateway/v1/virtualpresence.go
  pkg/client/listers/cloudgateway/v1/epolicy.go
  pkg/client/listers/cloudgateway/v1/eserver.go
  pkg/client/listers/cloudgateway/v1/virtualpresence.go
  pkg/cloudgateway/controller/controller.go
Labels: size/XXL

#712 add cloudgateway message processing
  pkg/cloudgateway/cloudhub/channelq/channelq.go
  pkg/cloudgateway/cloudhub/common/model/types.go
  pkg/cloudgateway/cloudhub/handler/messagehandler.go
  pkg/edgegateway/edgehub/process.go
Labels: size/L

#714 add edgegateway message processing
  pkg/cloudgateway/cloudhub/channelq/channelq.go
  pkg/cloudgateway/cloudhub/handler/messagehandler.go
  pkg/cloudgateway/common/constants/default.go
  pkg/edgegateway/common/constants/default.go
  pkg/edgegateway/edgehub/edgehub.go
  pkg/edgegateway/edgehub/process.go
Labels: size/L

#705 Fix issue that no hostIP sent to grpc server
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/util.go
Labels: size/S

#710 mizar grpc proto schema change
  pkg/controller/mizar/builtins.pb.go
  pkg/controller/mizar/builtins.proto
  pkg/controller/mizar/util.go
Labels: size/L

#715 Mizar network controllers for arktos network and services
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/grpc-adaptor.go
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-service-controller.go
  pkg/controller/mizar/util.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy_test.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: size/XL

#706 Initialize WorkloadInfo during defaulting
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  hack/arktos-up.sh
  pkg/apis/core/v1/BUILD
  pkg/apis/core/v1/defaults.go
  pkg/features/kube_features.go
Labels: size/S

#728 arktos-up: install network crd before waiting for node ready
  hack/arktos-up.sh
Labels: size/XS

#722 enable network_template_path in starting kube-controller-manager in a…
  hack/lib/common.sh
  hack/runtime/default_flat_network.json
Labels: size/S

#720 fix name problem
  cmd/cloudgateway/app/options/options.go
  cmd/edgegateway/app/options/options.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/apis/edgegateway/v1/types.go
  pkg/cloudgateway/cloudhub/channelq/channelq.go
  pkg/cloudgateway/cloudhub/common/model/types.go
  pkg/cloudgateway/cloudhub/handler/messagehandler.go
  pkg/cloudgateway/cloudhub/servers/httpserver/server.go
  pkg/edgegateway/common/constants/default.go
  pkg/edgegateway/edgehub/certificate/certmanager.go
  pkg/edgegateway/edgehub/clients/factory.go
  pkg/edgegateway/edgehub/clients/quicclient/quicclient.go
  pkg/edgegateway/edgehub/clients/wsclient/websocket.go
  pkg/edgegateway/edgehub/common/http/http.go
  pkg/edgegateway/edgehub/config/config.go
Labels: size/L

#709 Aggregated watcher recover
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
  staging/src/k8s.io/apimachinery/pkg/watch/watch_test.go
  staging/src/k8s.io/client-go/tools/cache/reflector.go
Labels: size/L

#734 fix kubectl-get-net error
  hack/arktos-up.sh
Labels: size/XS

#736 arktos-up: installs the common cni binary package for the external cni plugin that will be installed later
  hack/arktos-cni.rc
  hack/arktos-up.sh
Labels: size/S

#735 clarifies current support of per-network kubernetes EPs
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
Labels: area/multi-tenancy, area/networking, documentation, size/XS

#733 add new module, cloudservice and edgeservice
  cmd/cloudgateway/app/options/options.go
  cmd/cloudgateway/app/server.go
  cmd/edgegateway/app/options/options.go
  cmd/edgegateway/app/server.go
  pkg/apis/cloudgateway/v1/types.go
  pkg/apis/edgegateway/v1/types.go
  pkg/cloudgateway/cloudhub/channelq/channelq.go
  pkg/cloudgateway/cloudhub/common/model/types.go
  pkg/cloudgateway/cloudhub/handler/messagehandler.go
  pkg/cloudgateway/cloudservice/cloudservice.go
  pkg/cloudgateway/cloudservice/httpservice/http.go
  pkg/cloudgateway/cloudservice/httpservice/httpserver.go
  pkg/cloudgateway/common/constants/default.go
  pkg/cloudgateway/common/modules/group.go
  pkg/cloudgateway/common/modules/name.go
  pkg/edgegateway/common/constants/default.go
  pkg/edgegateway/common/modules/group.go
  pkg/edgegateway/common/modules/names.go
  pkg/edgegateway/edgehub/process.go
  pkg/edgegateway/edgeservice/edgeservice.go
  pkg/edgegateway/edgeservice/httpservice/http.go
  pkg/edgegateway/edgeservice/httpservice/httpclient.go
  pkg/edgegateway/edgeservice/router.go
Labels: size/L

#721 documents the steps of arktos enforcing network feature
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
  docs/setup-guide/arktos-enforces-netowrk-feature.md
  docs/setup-guide/multi-node-dev-cluster.md
Labels: area/multi-tenancy, area/networking, documentation, size/M

#739 Feature com data flow
  pkg/cloudgateway/controller/controller.go
  pkg/cloudgateway/controller/handler/handler.go
  pkg/cloudgateway/controller/handler/serviceexpose_handler.go
Labels: size/L

#741 cloud-edge service communication with http
  pkg/cloudgateway/cloudhub/channelq/channelq.go
  pkg/cloudgateway/cloudhub/handler/messagehandler.go
  pkg/cloudgateway/cloudservice/cloudservice.go
  pkg/cloudgateway/cloudservice/httpservice/httpclient.go
  pkg/cloudgateway/cloudservice/router.go
  pkg/cloudgateway/common/modules/name.go
  pkg/edgegateway/common/modules/group.go
  pkg/edgegateway/edgehub/process.go
  pkg/edgegateway/edgeservice/edgeservice.go
  pkg/edgegateway/edgeservice/httpservice/httpserver.go
Labels: size/L

#744 coredns pod connects to kube-apiserver directly
  cmd/arktos-network-controller/app/controller.go
  cmd/arktos-network-controller/app/controller_test.go
  cmd/arktos-network-controller/app/dns_deployment.go
  cmd/arktos-network-controller/app/dns_deployment_test.go
  cmd/arktos-network-controller/network-controller.go
  docs/setup-guide/arktos-enforces-netowrk-feature.md
Labels: size/M

#746 Modify service controller
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-service-controller.go
Labels: size/L

#748 fix the bug in setup_client.sh when the context to remove is current …
  hack/setup-multi-tenancy/setup_client.sh
Labels: size/XS

#753 Fix tiny issue found during testing: info should be infof
  pkg/controller/mizar/mizar-service-controller.go
Labels: size/S

#751 get service and site by gateway client
  cmd/cloudgateway/app/server.go
  pkg/cloudgateway/cloudhub/cloudhub.go
  pkg/cloudgateway/cloudhub/config/config.go
  pkg/cloudgateway/cloudhub/servers/httpserver/secretsutil.go
  pkg/cloudgateway/cloudhub/servers/httpserver/server.go
  pkg/cloudgateway/cloudhub/utils/gatewayclient.go
  pkg/cloudgateway/cloudhub/utils/kubeclient.go
  pkg/cloudgateway/cloudservice/httpservice/httpserver.go
  pkg/cloudgateway/cloudservice/router.go
  pkg/cloudgateway/cloudservice/utils/utils.go
Labels: size/L

#749 add switch to set --leader-elect=false for kube-scheduler
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  staging/src/k8s.io/apimachinery/pkg/watch/watch_test.go
Labels: size/S

#755 install cni binary package on arktos worker node
  docs/setup-guide/arktos-enforces-netowrk-feature.md
  hack/arktos-worker-up.sh
Labels: size/XS

#465 update multi-tenancy design doc about forced-sharing CRD
  docs/design-proposals/multi-tenancy/multi-tenancy-api-resource-model.md
Labels: size/M

#757 Added a missing quote in etcd.manifest
  cluster/gce/manifests/etcd.manifest
Labels: size/XS

#761 update doc per feedback from the Mizar team
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
  docs/setup-guide/arktos-enforces-network-feature.md
  docs/setup-guide/multi-node-dev-cluster.md
  hack/lib/common.sh
  hack/runtime/default_mizar_network.json
Labels: size/L
