Repository CentaurusInfra/arktos, pull requests merged in 2020-07, with the labels that each got.

#427 kubelet checks network readiness
  docs/design-proposals/multi-tenancy/images/pod-activity-diagram.png
  pkg/kubelet/BUILD
  pkg/kubelet/events/event.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_test.go
  plugin/pkg/admission/defaultpodnetworkreadiness/BUILD
  plugin/pkg/admission/defaultpodnetworkreadiness/admission.go
  plugin/pkg/admission/defaultpodnetworkreadiness/admission_test.go
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/types.go
Labels: area/multi-tenancy, area/networking, area/node-agent

#412 using new tenanted user info in integration tests
  staging/src/k8s.io/apiserver/pkg/authentication/group/group_adder.go
  staging/src/k8s.io/apiserver/pkg/authentication/group/group_adder_test.go
  test/integration/auth/accessreview_test.go
  test/integration/auth/auth_test.go
  test/integration/auth/rbac_test.go
  test/integration/master/synthetic_master_test.go
Labels: size/L

#450 increase apimachinery integration test tiemout
  test/integration/apimachinery/BUILD
  test/integration/master/BUILD
Labels: size/XS

#418 Vertical Scaling for VMs (in addition to containers)
  pkg/apis/core/types.go
  pkg/kubelet/BUILD
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/util/podConverter/podConverter.go
  plugin/pkg/admission/podresourceallocation/admission.go
  plugin/pkg/admission/podresourceallocation/admission_test.go
  staging/src/k8s.io/api/core/v1/types.go
Labels: size/L

#351 design doc: network policy in arktos
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
Labels: area/multi-tenancy, area/networking, documentation, size/L

#430 fix --partition-config to pickup apiserver-config from /etc/srv/kube…
  cluster/gce/gci/configure-helper-common.sh
Labels: size/XS

#451 ETCD partition part 3: support paginated list
  pkg/apis/core/validation/validation.go
  pkg/controller/tenant/tenant_controller.go
  pkg/registry/core/storagecluster/storage/storage_test.go
  staging/src/k8s.io/apimachinery/pkg/util/diff/compare.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/errors.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/test_server.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/interfaces.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/storageclustermanager.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/update.go
  test/integration/etcd/data.go
  test/integration/etcd/multi_tenancy_data.go
  test/integration/etcd/server.go
  test/integration/framework/util.go
  test/integration/kubelet/watch_manager_test.go
  test/integration/tenantcontroller/tenantcontroller_test.go
Labels: area/scalability, size/XL

#460 remove out-dated code in request.go
  staging/src/k8s.io/client-go/rest/request.go
Labels: size/XS

#464 fix kubectl-create-tenant break due to StorageClusterId type change
  pkg/kubectl/cmd/create/create_tenant.go
  pkg/kubectl/generate/versioned/BUILD
  pkg/kubectl/generate/versioned/tenant.go
  pkg/kubectl/generate/versioned/tenant_test.go
Labels: size/M

#452 Multi tenancy/kubectl rollout/scale
  pkg/kubectl/cmd/rollingupdate/rollingupdate.go
  pkg/kubectl/cmd/rollout/rollout_history.go
  pkg/kubectl/cmd/rollout/rollout_pause.go
  pkg/kubectl/cmd/rollout/rollout_restart.go
  pkg/kubectl/cmd/rollout/rollout_resume.go
  pkg/kubectl/cmd/rollout/rollout_status.go
  pkg/kubectl/cmd/rollout/rollout_undo.go
  pkg/kubectl/cmd/scale/scale.go
  pkg/kubectl/history.go
  pkg/kubectl/rollback.go
  pkg/kubectl/rolling_updater.go
  pkg/kubectl/rolling_updater_test.go
  pkg/kubectl/scale.go
  pkg/kubectl/scale_test.go
  pkg/kubectl/util/deployment/deployment.go
  staging/src/k8s.io/client-go/scale/BUILD
  staging/src/k8s.io/client-go/scale/client.go
  staging/src/k8s.io/client-go/scale/fake/BUILD
  staging/src/k8s.io/client-go/scale/fake/client.go
  staging/src/k8s.io/client-go/scale/interfaces.go
  test/utils/update_resources.go
Labels: size/L

#422 Not to assign ClusterIP for service whose associated network is of External IPAM type
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
  pkg/controller/artifacts/crd-network.yaml
  pkg/registry/core/service/storage/BUILD
  pkg/registry/core/service/storage/rest.go
  pkg/registry/core/service/storage/rest_test.go
  plugin/pkg/admission/defaultpodnetworkreadiness/BUILD
  plugin/pkg/admission/defaultpodnetworkreadiness/admission_test.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  staging/src/k8s.io/arktos-ext/go.mod
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/types.go
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/zz_generated.deepcopy.go
Labels: area/multi-tenancy, area/networking, size/L

#419 Design doc for Arktos VM & Container Vertical Scaling, updates to Action framework doc
  docs/design-proposals/apiserver/Action-API-design.md
  docs/design-proposals/node/Unified-Vertical-Scaling-for-Container-and-VM-Pods
Labels: size/L

#469 k8s endpoints read-only sharing: able to get, unable to create or update
  pkg/registry/core/endpoint/storage/BUILD
  pkg/registry/core/endpoint/storage/storage.go
  pkg/registry/core/endpoint/storage/storage_test.go
  pkg/registry/core/endpoint/strategy.go
Labels: area/multi-tenancy, area/networking, size/L

#474 Make useful log for performance test permanent.
  pkg/controller/volume/attachdetach/cache/desired_state_of_world.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/client-go/tools/cache/reflector.go
Labels: area/performance-test, size/S

#473 Add ETCD data partition into manual
  docs/design-proposals/etcd/ETCD-Data-Partition-Design.md
  docs/setup-guide/arktos-apiserver-partition.md
Labels: area/scalability, documentation, size/M

#484 per-network service IP allocation - part 1: feature gate and preparation refactoring
  pkg/features/kube_features.go
  pkg/registry/core/service/storage/BUILD
  pkg/registry/core/service/storage/rest.go
  pkg/registry/core/service/storage/rest_test.go
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/types.go
Labels: area/multi-tenancy, area/networking, size/L

#487 Fixed the kube-up start failure issue
  hack/apiserver.config
  hack/lib/common.sh
Labels: size/M

#413 Fix arktos-up bug so that kubectl always uses kubeconfig generated for arktos local cluster
  hack/arktos-up.sh
Labels: size/XS

#481 fix issue 479
  staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go
Labels: In Review, size/S

#472 More kubectl multi tenancy
  pkg/kubectl/cmd/apply/apply_set_last_applied.go
  pkg/kubectl/cmd/apply/apply_test.go
  pkg/kubectl/cmd/apply/apply_view_last_applied.go
  pkg/kubectl/cmd/diff/diff.go
  pkg/kubectl/cmd/edit/BUILD
  pkg/kubectl/cmd/edit/edit_test.go
  pkg/kubectl/cmd/edit/testdata/record.go
  pkg/kubectl/cmd/edit/testdata/testcase-apply-edit-last-applied-list-fail/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-apply-edit-last-applied-list/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-apply-edit-last-applied-syntax-error/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-apply-edit-last-applied/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-create-list-error/0.original
  pkg/kubectl/cmd/edit/testdata/testcase-create-list-error/2.original
  pkg/kubectl/cmd/edit/testdata/testcase-create-list/0.original
  pkg/kubectl/cmd/edit/testdata/testcase-create-list/2.original
  pkg/kubectl/cmd/edit/testdata/testcase-edit-from-empty/0.response
  pkg/kubectl/cmd/edit/testdata/testcase-edit-from-empty/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-immutable-name/0.response
  pkg/kubectl/cmd/edit/testdata/testcase-immutable-name/1.edited
  pkg/kubectl/cmd/edit/testdata/testcase-immutable-name/1.original
  pkg/kubectl/cmd/edit/testdata/testcase-immutable-name/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/0.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/1.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/10.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/2.edited
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/2.original
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/4.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/5.edited
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/5.original
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/7.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/8.edited
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/8.original
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/9.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-errors/test.yaml
  pkg/kubectl/cmd/edit/testdata/testcase-list-record/0.response
  pkg/kubectl/cmd/edit/testdata/testcase-list-record/2.edited
  pkg/kubectl/cmd/edit/testdata/testcase-list-record/2.original
  pkg/kubectl/cmd/edit/testdata/testcase-list-record/3.response
  pkg/kubectl/cmd/edit/testdata/testcase-list/0.response
  pkg/kubectl/cmd/edit/testdata/testcase-list/2.edited
  pkg/kubectl/cmd/edit/testdata/testcase-list/2.original
  pkg/kubectl/cmd/edit/testdata/testcase-list/3.response
  pkg/kubectl/cmd/replace/replace.go
  pkg/kubectl/cmd/replace/replace_test.go
  pkg/kubectl/cmd/set/env/env_resolve.go
  pkg/kubectl/cmd/set/set_env.go
  pkg/kubectl/cmd/set/set_env_test.go
  pkg/kubectl/cmd/set/set_image.go
  pkg/kubectl/cmd/set/set_image_test.go
  pkg/kubectl/cmd/set/set_resources.go
  pkg/kubectl/cmd/set/set_resources_test.go
  pkg/kubectl/cmd/set/set_selector.go
  pkg/kubectl/cmd/set/set_serviceaccount.go
  pkg/kubectl/cmd/set/set_serviceaccount_test.go
  pkg/kubectl/cmd/set/set_subject.go
  pkg/kubectl/cmd/util/editor/editoptions.go
  pkg/kubectl/describe/versioned/describe.go
  test/fixtures/pkg/kubectl/cmd/apply/patch.json
Labels: In Review, size/L

#497 Update scripts to be more compatible with sudo and also correct a comment typo
  build/root/Makefile
  hack/setup-dev-node.sh
Labels: size/XS

#499 Miscellous performance fix for api server partition:
  cmd/kube-proxy/app/BUILD
  cmd/kube-proxy/app/server.go
  cmd/kubelet/app/BUILD
  cmd/kubelet/app/server.go
  cmd/kubemark/BUILD
  cmd/kubemark/hollow-node.go
  pkg/master/BUILD
  pkg/master/controller.go
  pkg/proxy/endpoints.go
  staging/src/k8s.io/apimachinery/pkg/types/BUILD
  staging/src/k8s.io/apimachinery/pkg/types/mastername.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/client-go/datapartition/BUILD
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
Labels: area/performance-test, size/L

#494 add extra workload-controller-manager start to kube-up and kubemark
  build/lib/release.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/BUILD
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/workloadcontroller-configure-helper.sh
  cluster/gce/gci/workloadcontroller-helper.sh
  cluster/gce/gci/workloadcontroller.yaml
  cluster/gce/util.sh
  cluster/validate-cluster.sh
Labels: size/XL

#488 kubectl e2e test script
  test/e2e/arktos/multi-tenancy/README.md
  test/e2e/arktos/multi-tenancy/helper/config-e2e-test.sh
  test/e2e/arktos/multi-tenancy/helper/e2e-test-helper.sh
  test/e2e/arktos/multi-tenancy/run-e2e-test.sh
  test/e2e/arktos/multi-tenancy/testcase/basic_tests
  test/e2e/arktos/multi-tenancy/testcase/new_tenant_tests
Labels: In Review, size/L

#503 change apiserver advertise-address to internal ip
  cluster/gce/gci/apiserver-helper.sh
  cluster/gce/util.sh
Labels: size/S

#490 arktos-up script to set forward chain accept by default
  hack/arktos-cni.rc
Labels: area/scalability, bug, size/XS

#492 per-network service IP allocation - part 2: implement method of getting service ip allocator per network
  pkg/registry/core/rest/storage_core.go
  pkg/registry/core/service/storage/BUILD
  pkg/registry/core/service/storage/rest.go
  pkg/registry/core/service/storage/rest_test.go
Labels: area/multi-tenancy, area/networking, size/L

#506 Enabled "make update" to install the expected version etcd
  hack/update-etcd.sh
Labels: size/S

#496 add checks for existance before calling apiserver
  cmd/kube-controller-manager/app/core.go
  pkg/controller/tenant/BUILD
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  test/integration/tenantcontroller/tenantcontroller_test.go
Labels: In Review, area/multi-tenancy, area/performance-test, size/L

#511 add internal IP to server cert
  cluster/gce/util.sh
Labels: size/S

#508 Fixed the a flaky test returns c1 or c2 randomly.
  cmd/kube-scheduler/app/options/options_test.go
Labels: size/M

#510 Fixing issue 505
  pkg/api/testapi/BUILD
  pkg/api/testapi/testapi.go
  pkg/api/testapi/testapi_test.go
  staging/src/k8s.io/client-go/tools/cache/listwatch.go
Labels: size/M

#524 Workload controller manager: use protobuf as request content instead of default json
  cmd/workload-controller-manager/BUILD
  cmd/workload-controller-manager/main.go
Labels: area/workload-controller-manager, size/S

#528 Configure QPS (20) for workload controller manager
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/workload-controller-manager/app/config/BUILD
  cmd/workload-controller-manager/app/config/controllerconfig.go
  cmd/workload-controller-manager/config/controllerconfig.json
  cmd/workload-controller-manager/main.go
Labels: area/workload-controller-manager, bug, size/M

#475 Fixed the issue that kube-up does not pick up etcd3.4.4-arktos.1
  cluster/common.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/gce/util.sh
  cluster/images/etcd-empty-dir-cleanup/Makefile
  cluster/images/etcd/Dockerfile
  cluster/images/etcd/Makefile
  cluster/images/etcd/README.md
  cluster/images/etcd/migrate-if-needed.sh
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/constants/constants_test.go
  vendor/go.etcd.io/etcd/version/version.go
Labels: size/L
