Repository CentaurusInfra/arktos, pull requests merged in 2020-08, with the labels that each got.

#533 Fix the picture link in README with raw URL
  README.md
  docs/README.md
Labels: size/XS

#540 add switch parameter to set kube-controller-manager --leader-elect=fa…
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
Labels: size/S

#541 Perf-test changes
  perf-tests/clusterloader2/cmd/BUILD
  perf-tests/clusterloader2/cmd/clusterloader.go
  perf-tests/clusterloader2/pkg/config/cluster.go
  perf-tests/clusterloader2/pkg/framework/BUILD
  perf-tests/clusterloader2/pkg/framework/config/BUILD
  perf-tests/clusterloader2/pkg/framework/config/client_config.go
  perf-tests/clusterloader2/pkg/framework/framework.go
  perf-tests/clusterloader2/pkg/test/simple_test_executor.go
  perf-tests/clusterloader2/pkg/util/util.go
  staging/src/k8s.io/client-go/dynamic/BUILD
  staging/src/k8s.io/client-go/dynamic/simple.go
Labels: area/performance-test, size/L

#542 support shared server for multi apiserver, workloadcontroller, etcd
  build/lib/release.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/BUILD
  cluster/gce/gci/apiserver-helper.sh
  cluster/gce/gci/apiserver.yaml
  cluster/gce/gci/configure.sh
  cluster/gce/gci/partitionserver-configure-helper.sh
  cluster/gce/gci/partitionserver-helper.sh
  cluster/gce/gci/partitionserver.yaml
  cluster/gce/gci/workloadcontroller-configure-helper.sh
  cluster/gce/util.sh
  cluster/validate-cluster.sh
Labels: size/XL

#544 Remove partition for secrets & serviceaccounts because create pod req…
  hack/apiserver.config
Labels: area/scalability, size/XS

#547 Updated a tenant test yaml file
  docs/setup-guide/arktos-apiserver-partition.md
Labels: size/XS

#550 allow setting master_root_disk_size when start kubemark
  test/kubemark/gce/util.sh
Labels: size/XS

#514 Update design doc with VM specific details
  docs/design-proposals/node/Unified-Vertical-Scaling-for-Container-and-VM-Pods
  docs/design-proposals/node/Unified-Vertical-Scaling-for-Container-and-VM-Pods.md
Labels: size/XL

#549 Bug fix for Workload controller Manager not stable issue
  cluster/aws/manifests/workload-controller-manager.manifest
  cluster/gce/manifests/workload-controller-manager.manifest
  cmd/workload-controller-manager/app/BUILD
  cmd/workload-controller-manager/app/controllermanager.go
  pkg/cloudfabric-controller/controllerframework/BUILD
  pkg/cloudfabric-controller/controllerframework/cim_test.go
  pkg/cloudfabric-controller/controllerframework/controller_framework.go
  pkg/cloudfabric-controller/controllerframework/controller_framework_test.go
  pkg/cloudfabric-controller/controllerframework/controller_framework_utils.go
  pkg/cloudfabric-controller/controllerframework/controller_framework_utils_test.go
  pkg/cloudfabric-controller/controllerframework/controllerinstancemanager.go
  pkg/cloudfabric-controller/deployment/deployment_controller.go
  pkg/cloudfabric-controller/deployment/progress_test.go
  pkg/cloudfabric-controller/deployment/rolling_test.go
  pkg/cloudfabric-controller/deployment/sync_test.go
  pkg/cloudfabric-controller/replicaset/replica_set.go
  pkg/cloudfabric-controller/replicaset/replica_set_test.go
  staging/src/k8s.io/client-go/datapartition/apiserverconfigmanager.go
  test/integration/cloudfabriccontrollers/BUILD
  test/integration/cloudfabriccontrollers/framework_test.go
Labels: area/performance-test, area/workload-controller-manager, bug, size/XXL

#554 Fix a timing issue where the pod.spec.workloadinfo can be used concurrently by PLEG and podUpdate routines
  pkg/apis/core/helper/qos/qos.go
  pkg/apis/core/v1/helper/qos/qos.go
Labels: size/S

#556 Miscellanous fix of WCM:
  cmd/workload-controller-manager/app/config/controllerconfig.go
  cmd/workload-controller-manager/app/controllermanager.go
  cmd/workload-controller-manager/config/controllerconfig.json
  pkg/cloudfabric-controller/controllerframework/controllerinstancemanager.go
  staging/src/k8s.io/client-go/tools/cache/reflector.go
Labels: size/M

#558 Bug fix for clientset generation
  cmd/kube-scheduler/app/server.go
  cmd/workload-controller-manager/app/BUILD
  cmd/workload-controller-manager/app/controllermanager.go
  cmd/workload-controller-manager/main.go
  staging/src/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/clientset.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/clientset.go
  staging/src/k8s.io/client-go/kubernetes/clientset.go
  staging/src/k8s.io/code-generator/_examples/MixedCase/clientset/versioned/clientset.go
  staging/src/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/clientset.go
  staging/src/k8s.io/code-generator/_examples/apiserver/clientset/versioned/clientset.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/clientset.go
  staging/src/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/clientset.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/internalclientset/clientset.go
  staging/src/k8s.io/metrics/pkg/client/clientset/versioned/clientset.go
  staging/src/k8s.io/node-api/pkg/client/clientset/versioned/clientset.go
  staging/src/k8s.io/sample-apiserver/pkg/generated/clientset/versioned/clientset.go
  staging/src/k8s.io/sample-controller/pkg/generated/clientset/versioned/clientset.go
Labels: bug, size/L

#580 Fix a nil pointer crash caused by a race condition in watch cache
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
Labels: size/S

#577 add apiserver data partition to kube-up and start-kubemark
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/util.sh
  cluster/kube-up.sh
  test/kubemark/start-kubemark.sh
Labels: size/L

#583 Re-Enable Prometheus Probers in Kubelet
  pkg/kubelet/apis/resourcemetrics/v1alpha1/BUILD
  pkg/kubelet/apis/resourcemetrics/v1alpha1/config.go
  pkg/kubelet/dockershim/network/testing/fake_host.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/prober/BUILD
  pkg/kubelet/prober/common_test.go
  pkg/kubelet/prober/prober.go
  pkg/kubelet/prober/prober_manager.go
  pkg/kubelet/prober/prober_manager_test.go
  pkg/kubelet/prober/prober_test.go
  pkg/kubelet/prober/results/results_manager.go
  pkg/kubelet/prober/testing/BUILD
  pkg/kubelet/prober/testing/fake_manager.go
  pkg/kubelet/prober/worker.go
  pkg/kubelet/prober/worker_test.go
  pkg/kubelet/server/BUILD
  pkg/kubelet/server/server.go
  pkg/kubelet/server/stats/BUILD
  pkg/kubelet/server/stats/handler.go
  pkg/kubelet/server/stats/prometheus_resource_metrics.go
  pkg/kubelet/server/stats/prometheus_resource_metrics_test.go
Labels: size/XL

#581 Update controller name generation logic for data distribution efficiency
  pkg/cloudfabric-controller/controllerframework/cim_test.go
  pkg/cloudfabric-controller/controllerframework/controller_framework.go
  pkg/cloudfabric-controller/controllerframework/controller_framework_test.go
  pkg/cloudfabric-controller/controllerframework/controller_framework_utils.go
  pkg/cloudfabric-controller/controllerframework/controllerinstancemanager.go
  pkg/cloudfabric-controller/replicaset/replica_set_test.go
  test/integration/cloudfabriccontrollers/deployment_util.go
  test/integration/cloudfabriccontrollers/framework_test.go
  test/integration/cloudfabriccontrollers/testutil.go
Labels: area/controller-manager, area/scalability, size/L

#591 make run-e2e.sh run without softlink
  perf-tests/clusterloader2/run-e2e.sh
Labels: size/XS

#592 Per discussion, add more log for issue 584
  pkg/cloudfabric-controller/deployment/deployment_controller.go
  pkg/cloudfabric-controller/replicaset/replica_set.go
Labels: size/S

#594 Update logging for more info to investigate stress related issues
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/util/format/pod.go
  pkg/volume/util/operationexecutor/operation_executor.go
Labels: size/M

#593 bug fix: scheduler node runtime readiness predicate should respect pod no-schedule toleration
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/predicates_test.go
Labels: size/M

#598 Enforce Rlock for pod-runtime map and use of map operation functions
  pkg/kubelet/kuberuntime/helpers.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
Labels: size/S

#597 Add pod create event to scheduler
  pkg/scheduler/eventhandlers.go
Labels: size/XS

#596 Increase UT test coverage for api server/etcd data partition - part 1
  pkg/master/BUILD
  pkg/master/controller_test.go
  pkg/master/reconcilers/BUILD
  pkg/master/reconcilers/lease_test.go
  pkg/printers/internalversion/printers_test.go
  pkg/registry/core/controllerinstance/storage/storage_test.go
  pkg/registry/core/storagecluster/storage/storage.go
Labels: size/L

#600 kubelet should not skip pod synchronization when network is not ready
  pkg/kubelet/kubelet.go
Labels: size/XS

#602 fix workload-controller-manager log level cannot be configured in kub…
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/util.sh
Labels: size/S

#604 UT coverage increase for vendor/apiserver/storage
  staging/src/k8s.io/apiserver/pkg/storage/datapartition/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/datapartition/datapartitionmanager_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/storageclustermanager_test.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager_test.go
Labels: area/scalability, size/XL

#617 add arktos worker node
  hack/arktos-worker-up.sh
Labels: size/M

#613 Update design documents for cloud-edge communication framework feature
  docs/design-proposals/cloud-edge-communication/cloud-edge-communication-framework.md
Labels: size/S

#614 Rewrite multi-tenancy e2e test tool in golang
  test/e2e/BUILD
  test/e2e/arktos/multi_tenancy/cmd/BUILD
  test/e2e/arktos/multi_tenancy/cmd/framework/BUILD
  test/e2e/arktos/multi_tenancy/cmd/framework/errors.go
  test/e2e/arktos/multi_tenancy/cmd/framework/testcase.go
  test/e2e/arktos/multi_tenancy/cmd/framework/testconfig.go
  test/e2e/arktos/multi_tenancy/cmd/framework/testsuite.go
  test/e2e/arktos/multi_tenancy/cmd/framework/util.go
  test/e2e/arktos/multi_tenancy/cmd/testrunner.go
  test/e2e/arktos/multi_tenancy/run-e2e-test.sh
  test/e2e/arktos/multi_tenancy/test_suites/tenant_init_delete_test.yaml
Labels: size/XL

#623 fix ALLOWED_NOTREADY_NODES for kubemark
  cluster/gce/config-test.sh
  cluster/validate-cluster.sh
Labels: size/XS

#625 remove old script based multi-tenancy e2e tests
  test/e2e/arktos/multi-tenancy/README.md
  test/e2e/arktos/multi-tenancy/helper/config-e2e-test.sh
  test/e2e/arktos/multi-tenancy/helper/e2e-test-helper.sh
  test/e2e/arktos/multi-tenancy/run-e2e-test.sh
  test/e2e/arktos/multi-tenancy/testcase/basic_tests
  test/e2e/arktos/multi-tenancy/testcase/new_tenant_tests
Labels: size/L

#629 e2e tests for deployment/replicaset/serviceacount/token/endpoints controllers
  test/e2e/arktos/multi_tenancy/run-e2e-test.sh
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_deployment_replicaset_controller.yaml
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_endpoints_controller.yaml
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_sa_token_controller.yaml
  test/e2e/arktos/multi_tenancy/testdata/sample-deployment.yaml
Labels: size/L

#632 doc: instruction of adding new worker nodes with quirk of k8s service iptables rule
  docs/setup-guide/multi-node-dev-cluster.md
Labels: size/M

#620 Added unit test cases for List & Watch Issue 61
  staging/src/k8s.io/apimachinery/pkg/fields/selector_test.go
  staging/src/k8s.io/apimachinery/pkg/runtime/conversion_test.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/BUILD
  staging/src/k8s.io/apiserver/pkg/registry/generic/matcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3_test.go
Labels: size/XL

#634 improve multi-tenancy e2e test tool
  test/e2e/arktos/multi_tenancy/cmd/framework/testcase.go
  test/e2e/arktos/multi_tenancy/cmd/framework/testsuite.go
  test/e2e/arktos/multi_tenancy/cmd/testrunner.go
  test/e2e/arktos/multi_tenancy/run-e2e-test.sh
  test/e2e/arktos/multi_tenancy/test_suites/multi_tenancy_controller/test_deployment_replicaset_controller.yaml
Labels: size/L

#635 Vertical Scaling: Fix CPU requests only update bug, add E2E tests.
  pkg/kubelet/cm/pod_container_manager_linux.go
  pkg/kubelet/cm/pod_container_manager_stub.go
  pkg/kubelet/cm/types.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  test/e2e/framework/util.go
  test/e2e/node/BUILD
  test/e2e/node/pod_resize.go
Labels: size/XXL

#649 Add CHANGELOG for release 0.5
  CHANGELOG/CHANGELOG-0.5.md
  CHANGELOG/README.md
Labels: size/M
