Repository CentaurusInfra/arktos, pull requests merged in 2020-06, with the labels that each got.

#328 ETCD data partition:
  cmd/kube-apiserver/app/BUILD
  cmd/kube-apiserver/app/options/options_test.go
  cmd/kube-apiserver/app/server.go
  pkg/master/BUILD
  pkg/master/master.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/objectmeta_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/pruning_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/storage/objectreader.go
  staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
  staging/src/k8s.io/apiserver/pkg/server/options/etcd_test.go
  staging/src/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  staging/src/k8s.io/apiserver/pkg/server/storage/storage_factory_test.go
  staging/src/k8s.io/apiserver/pkg/storage/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/datapartition/datapartitionmanager.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd/util/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/test_server.go
  staging/src/k8s.io/apiserver/pkg/storage/interfaces.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/tls_test.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/storageclustermanager.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/update.go
  test/integration/etcd/server.go
  test/integration/examples/apiserver_test.go
  test/integration/framework/master_utils.go
  test/integration/framework/test_server.go
  test/integration/utils.go
Labels: area/scalability

#335 make cron job controller multi-tenant
  pkg/controller/cronjob/cronjob_controller.go
  pkg/controller/cronjob/cronjob_controller_test.go
  pkg/controller/cronjob/injection.go
  pkg/controller/cronjob/utils_test.go
  test/integration/cronjob/cronjob_test.go
Labels: In Review, area/multi-tenancy

#306 install-kata.sh calls kubectl.sh in bootstrap process
  hack/arktos-up.sh
  hack/install-kata.sh
Labels: bug

#352 added scripts and guide for user to setup tenant and access
  docs/setup-guide/multi-tenancy-setup.md
  hack/setup-multi-tenancy/create_tenant.sh
  hack/setup-multi-tenancy/setup_client.sh
Labels: area/multi-tenancy, size/L

#330 Refactor runtime northbound API for multiple runtime service support
  pkg/kubelet/BUILD
  pkg/kubelet/cm/BUILD
  pkg/kubelet/cm/container_manager.go
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/cm/container_manager_stub.go
  pkg/kubelet/cm/container_manager_unsupported.go
  pkg/kubelet/cm/container_manager_windows.go
  pkg/kubelet/cm/cpumanager/BUILD
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  pkg/kubelet/container/BUILD
  pkg/kubelet/container/fake_runtime_manager.go
  pkg/kubelet/container/runtime.go
  pkg/kubelet/images/image_gc_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_node_status_test.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/kuberuntime/BUILD
  pkg/kubelet/kuberuntime/fake_kuberuntime_manager.go
  pkg/kubelet/kuberuntime/helpers.go
  pkg/kubelet/kuberuntime/helpers_test.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_image.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_sandbox.go
  pkg/kubelet/logs/BUILD
  pkg/kubelet/logs/container_log_manager.go
  pkg/kubelet/logs/container_log_manager_test.go
  pkg/kubelet/pod_container_deletor.go
  pkg/kubelet/runtimeregistry/BUILD
  pkg/kubelet/runtimeregistry/fake_runtime_manager.go
  pkg/kubelet/runtimeregistry/kuberuntime_registry.go
  pkg/kubelet/runtimeregistry/kuberuntime_registry_test.go
  pkg/kubelet/stats/BUILD
  pkg/kubelet/stats/cadvisor_stats_provider.go
  pkg/kubelet/stats/cri_stats_provider.go
  pkg/kubelet/stats/cri_stats_provider_test.go
  pkg/kubelet/stats/stats_provider.go
Labels: size/XXL

#313 multi-tenancy: flat network controller
  cmd/BUILD
  cmd/flat-network-controller/BUILD
  cmd/flat-network-controller/app/BUILD
  cmd/flat-network-controller/app/controller.go
  cmd/flat-network-controller/app/controller_test.go
  cmd/flat-network-controller/flat-network-controller.go
  pkg/controller/artifacts/crd-network.yaml
  staging/src/k8s.io/arktos-ext/go.mod
  staging/src/k8s.io/arktos-ext/go.sum
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/types.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/arktosextensions_client.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/fake/fake_arktosextensions_client.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/network.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/interface.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/v1/interface.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/v1/network.go
  staging/src/k8s.io/arktos-ext/pkg/generated/listers/arktosextensions/v1/network.go
Labels: area/multi-tenancy, area/networking, size/XL

#361 update Tenantallexplicit in generic.go to import from apimachinery
  cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
  cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go
  pkg/kubelet/BUILD
  pkg/kubelet/cm/BUILD
  pkg/kubelet/cm/cpumanager/BUILD
  pkg/kubelet/container/BUILD
  pkg/kubelet/kuberuntime/BUILD
  pkg/kubelet/kuberuntime/fake_kuberuntime_manager.go
  pkg/kubelet/logs/BUILD
  pkg/kubelet/pod_container_deletor.go
  pkg/kubelet/runtimeregistry/BUILD
  pkg/kubelet/runtimeregistry/fake_runtime_manager.go
  pkg/kubelet/runtimeregistry/kuberuntime_registry.go
  pkg/kubelet/stats/BUILD
  pkg/kubelet/stats/cri_stats_provider.go
  plugin/pkg/admission/tenant/exists/admission.go
  staging/src/k8s.io/apimachinery/pkg/api/validation/BUILD
  staging/src/k8s.io/apimachinery/pkg/api/validation/generic.go
Labels: size/M

#356 tenant deleter
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/core.go
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/types.go
  pkg/controller/tenant/BUILD
  pkg/controller/tenant/deletion/BUILD
  pkg/controller/tenant/deletion/tenanted_resources_deleter.go
  pkg/controller/tenant/deletion/tenanted_resources_deleter_test.go
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  pkg/registry/core/tenant/strategy.go
  pkg/registry/core/tenant/strategy_test.go
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/BUILD
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/fake/BUILD
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/fake/fake_tenant_expansion.go
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/generated_expansion.go
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/tenant_expansion.go
Labels: area/multi-tenancy, size/XXL

#343 In-place Pod Vertical Scaling for Container Pods - core KEP implement…
  pkg/api/resource/helpers.go
  pkg/api/v1/resource/helpers.go
  pkg/kubectl/describe/versioned/BUILD
  pkg/kubectl/describe/versioned/describe.go
  pkg/kubectl/describe/versioned/describe_test.go
  pkg/kubectl/describe/versioned/multi_tenancy_describe_test.go
  pkg/kubectl/util/resource/resource.go
  pkg/kubelet/BUILD
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cpumanager/BUILD
  pkg/kubelet/cm/cpumanager/policy_static.go
  pkg/kubelet/cm/helpers_linux.go
  pkg/kubelet/cm/pod_container_manager_linux.go
  pkg/kubelet/cm/pod_container_manager_stub.go
  pkg/kubelet/cm/qos_container_manager_linux.go
  pkg/kubelet/cm/types.go
  pkg/kubelet/container/BUILD
  pkg/kubelet/container/helpers.go
  pkg/kubelet/container/helpers_test.go
  pkg/kubelet/container/runtime.go
  pkg/kubelet/eviction/helpers.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_pods_test.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/kuberuntime/BUILD
  pkg/kubelet/kuberuntime/helpers_linux.go
  pkg/kubelet/kuberuntime/helpers_linux_test.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_container_linux.go
  pkg/kubelet/kuberuntime/kuberuntime_container_test.go
  pkg/kubelet/kuberuntime/kuberuntime_container_windows.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  pkg/kubelet/preemption/BUILD
  pkg/kubelet/preemption/preemption.go
  pkg/kubelet/qos/BUILD
  pkg/kubelet/qos/policy.go
  pkg/scheduler/algorithm/predicates/predicates.go
  plugin/pkg/admission/podresourceallocation/admission.go
  plugin/pkg/admission/podresourceallocation/admission_test.go
Labels: size/XXL

#357 ETCD data partition part 2
  cmd/kube-apiserver/app/server.go
  hack/apiserver.config
  pkg/master/master.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/BUILD
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/options/BUILD
  staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/options/options.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/test_server.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/interfaces.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/storageclustermanager.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/tenantstoragemapmanager.go
  staging/src/k8s.io/apiserver/pkg/storage/storagecluster/update.go
  staging/src/k8s.io/apiserver/pkg/storage/tests/cacher_test.go
  test/integration/etcd/data.go
  test/integration/etcd/multi_tenancy_data.go
  test/integration/framework/BUILD
  test/integration/framework/master_utils.go
Labels: area/scalability, size/XL

#364 "make update" should return 1 if there is file updated.
  hack/make-rules/update.sh
Labels: area/cicd, size/S

#363 admission controller: annotates pod network-readiness=false by default
  pkg/kubeapiserver/options/BUILD
  pkg/kubeapiserver/options/plugins.go
  plugin/BUILD
  plugin/pkg/admission/defaultpodnetworkreadiness/BUILD
  plugin/pkg/admission/defaultpodnetworkreadiness/admission.go
  plugin/pkg/admission/defaultpodnetworkreadiness/admission_test.go
Labels: area/multi-tenancy, area/networking, size/L

#372 Add a flag IS_DRY_RUN which will be used in Jenkins CI
  aws_kube_params.inc
  cluster/aws/util.sh
  cluster/kube-up.sh
Labels: area/cicd, size/M

#385 apiserver partition start up script refactor:
  docs/setup-guide/arktos-apiserver-partition.md
  hack/arktos-apiserver-partition.sh
  hack/lib/common.sh
Labels: area/scalability, size/L

#378 add integration test for tenant cluster role and binding provisioning
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  test/integration/BUILD
  test/integration/tenantcontroller/BUILD
  test/integration/tenantcontroller/main_test.go
  test/integration/tenantcontroller/tenantcontroller_test.go
Labels: area/multi-tenancy, size/L, stabilization

#368 Added Customized ETCD v3.4.4.1 into arktos repo
  cluster/images/etcd/Makefile
  hack/lib/etcd.sh
Labels: area/scalability, size/S

#397 Fix issue that kubemark cannot start, error: permission denied when copying .kube config
  cluster/aws/util.sh
Labels: size/XS

#382 In-place Pod Vertical Scaling - add resource-quota & limit-ranger support
  pkg/kubelet/kubelet.go
  pkg/quota/v1/evaluator/core/pods.go
  plugin/pkg/admission/limitranger/BUILD
  plugin/pkg/admission/limitranger/admission.go
  plugin/pkg/admission/resourcequota/BUILD
  plugin/pkg/admission/resourcequota/controller.go
Labels: size/M

#341 design doc: pod annotations as hint & cni args
  docs/design-proposals/multi-tenancy/images/pod-activity-diagram.png
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
Labels: area/multi-tenancy, area/networking, documentation

#398 Updated etcd version from 3.4.4.1 to 3.4.4-arktos.1
  cluster/images/etcd/Makefile
  hack/lib/etcd.sh
Labels: size/XS

#383 Multi tenancy kubectl commands
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/kubectl/cmd/annotate/annotate.go
  pkg/kubectl/cmd/autoscale/autoscale.go
  pkg/kubectl/cmd/clusterinfo/clusterinfo.go
  pkg/kubectl/cmd/cp/cp.go
  pkg/kubectl/cmd/cp/cp_test.go
  pkg/kubectl/cmd/create/create_job.go
  pkg/kubectl/cmd/diff/diff.go
  pkg/kubectl/cmd/drain/drain.go
  pkg/kubectl/cmd/drain/drain_test.go
  pkg/kubectl/cmd/expose/expose.go
  pkg/kubectl/cmd/label/label.go
  pkg/kubectl/cmd/patch/patch.go
  pkg/kubectl/cmd/run/run.go
  pkg/kubectl/cmd/run/run_test.go
  pkg/kubectl/cmd/taint/taint.go
  pkg/kubectl/drain/drain.go
  pkg/kubectl/drain/filters.go
Labels: size/L

#399 create system tenant at tenant controller bootstrap
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  test/integration/tenantcontroller/tenantcontroller_test.go
Labels: size/M

#410 Fix unlock of unlocked mutex bug in api server endpoints update
  staging/src/k8s.io/client-go/apiserverupdate/update.go
Labels: area/scalability, size/XS, stabilization

#405 multi-tenancy resource quota controller (per tenant)
  pkg/controller/resourcequota/resource_quota_controller.go
  pkg/controller/resourcequota/resource_quota_controller_test.go
  pkg/controller/resourcequota/resource_quota_monitor.go
  pkg/quota/v1/evaluator/core/persistent_volume_claims.go
  pkg/quota/v1/evaluator/core/pods.go
  pkg/quota/v1/evaluator/core/services.go
  pkg/quota/v1/generic/evaluator.go
  pkg/quota/v1/interfaces.go
  pkg/quota/v1/resources.go
  plugin/pkg/admission/resourcequota/admission.go
  plugin/pkg/admission/resourcequota/admission_test.go
  plugin/pkg/admission/resourcequota/controller.go
  plugin/pkg/admission/resourcequota/resource_access.go
  test/integration/quota/BUILD
  test/integration/quota/quota_test.go
Labels: In Review, area/multi-tenancy, size/L

#409 Bug fix for script that start 2nd api server
  hack/arktos-apiserver-partition.sh
  hack/lib/common.sh
Labels: bug, size/M

#411 fix issue 377
  pkg/registry/rbac/validation/BUILD
  pkg/registry/rbac/validation/rule.go
Labels: In Review, size/M

#407 Added etcd to make update
  hack/install-etcd.sh
  hack/lib/etcd.sh
  hack/make-rules/update.sh
  hack/update-etcd.sh
Labels: size/M

#414 Fix "send on closed channel" bug in aggregated watch
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
Labels: area/scalability, size/S, stabilization

#416 add setup script info to readme
  README.md
Labels: documentation, size/XS

#404 Add cluster-id to ETCD start argument
  hack/lib/etcd.sh
Labels: size/XS

#299 Fixed the scheduler throughput issue - controller instance update
  cmd/workload-controller-manager/app/BUILD
  cmd/workload-controller-manager/app/controllermanager.go
  cmd/workload-controller-manager/config/controllerconfig.json
  pkg/cloudfabric-controller/BUILD
  pkg/cloudfabric-controller/controllerframework/controllerinstancemanager.go
  pkg/cloudfabric-controller/informer_factory.go
Labels: do-not-merge, size/M

#424 add missing rule policy to tenant admin clusterrole
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
Labels: area/multi-tenancy, bug, size/S

#415 Ensure looping through all runtime services in querying containerID or sandboxID
  pkg/kubelet/kuberuntime/helpers.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
Labels: size/M

#421 Update setup guide doc
  docs/setup-guide/arktos-apiserver-partition.md
  docs/setup-guide/multi-node-dev-cluster.md
  docs/setup-guide/setup-dev-env.md
Labels: documentation, size/M

#428 Etcd partition - solving too old resource version issue for multi partitions list
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  test/integration/auth/auth_test.go
  test/integration/auth/bootstraptoken_test.go
  test/integration/auth/rbac_test.go
Labels: area/scalability, size/M
