Repository CentaurusInfra/arktos, pull requests merged in 2020-05, with the labels that each got.

#236 pod, pv and pvc with multi-tenancy
  pkg/controller/volume/attachdetach/attach_detach_controller.go
  pkg/controller/volume/attachdetach/attach_detach_controller_test.go
  pkg/controller/volume/attachdetach/metrics/metrics.go
  pkg/controller/volume/attachdetach/metrics/metrics_test.go
  pkg/controller/volume/attachdetach/util/util.go
  pkg/controller/volume/expand/cache/volume_resize_map.go
  pkg/controller/volume/persistentvolume/framework_test.go
  pkg/controller/volume/persistentvolume/index.go
  pkg/controller/volume/persistentvolume/provision_test.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/controller/volume/persistentvolume/pv_controller_base.go
  pkg/controller/volume/persistentvolume/pv_controller_test.go
  pkg/controller/volume/persistentvolume/util/util.go
  pkg/controller/volume/pvcprotection/pvc_protection_controller.go
  pkg/controller/volume/pvcprotection/pvc_protection_controller_test.go
  pkg/controller/volume/pvprotection/pv_protection_controller.go
  pkg/controller/volume/pvprotection/pv_protection_controller_test.go
  pkg/controller/volume/scheduling/scheduler_assume_cache.go
  pkg/controller/volume/scheduling/scheduler_assume_cache_test.go
  pkg/controller/volume/scheduling/scheduler_binder.go
  pkg/controller/volume/scheduling/scheduler_binder_test.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/scheduler/algorithm/predicates/csi_volume_predicate.go
  pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go
  pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/testing_helper.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/volume/util/resize_util.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  test/integration/scheduler/extender_test.go
  test/integration/scheduler/predicates_test.go
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/util.go
  test/integration/scheduler/volume_binding_test.go
  test/integration/volume/attach_detach_test.go
  test/integration/volume/persistent_volumes_test.go
Labels: area/multi-tenancy

#259 fix issue: https://github.com/futurewei-cloud/arktos/issues/240
  test/kubemark/start-kubemark.sh
Labels: area/performance-test

#247 multi-tenancy networking: defines CRD of network
  pkg/controller/artifacts/README.md
  pkg/controller/artifacts/crd-network.yaml
Labels: area/multi-tenancy, area/networking

#206 design doc: service in multi-tenancy networking
  docs/design-proposals/multi-tenancy/images/network-c-and-c.gliffy
  docs/design-proposals/multi-tenancy/images/network-c-and-c.png
  docs/design-proposals/multi-tenancy/images/network-data-model.gliffy
  docs/design-proposals/multi-tenancy/images/network-data-model.png
  docs/design-proposals/multi-tenancy/images/network-module-decomposition.gliffy
  docs/design-proposals/multi-tenancy/images/network-module-decomposition.png
  docs/design-proposals/multi-tenancy/images/network-resource-isolation.png
  docs/design-proposals/multi-tenancy/images/network-scenario-tenant-init.gliffy
  docs/design-proposals/multi-tenancy/images/network-scenario-tenant-init.png
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
Labels: area/multi-tenancy, area/networking

#263 Add document "How to run e2e test in local dev environment"
  docs/setup-guide/run-e2e-test-locally.md
  docs/setup-guide/setup-dev-env.md
Labels: documentation

#271 add multi-tenancy to statefulset
  pkg/api/v1/pod/util.go
  pkg/controller/history/controller_history.go
  pkg/controller/statefulset/stateful_pod_control.go
  pkg/controller/statefulset/stateful_set.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_status_updater.go
  pkg/controller/statefulset/stateful_set_test.go
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controller/statefulset/stateful_set_utils_test.go
  pkg/controller/volume/attachdetach/attach_detach_controller_test.go
  pkg/controller/volume/attachdetach/metrics/metrics.go
  pkg/controller/volume/attachdetach/metrics/metrics_test.go
  pkg/controller/volume/attachdetach/util/util.go
  pkg/controller/volume/expand/cache/volume_resize_map.go
  pkg/controller/volume/persistentvolume/framework_test.go
  pkg/controller/volume/persistentvolume/index.go
  pkg/controller/volume/persistentvolume/provision_test.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/controller/volume/persistentvolume/pv_controller_test.go
  pkg/controller/volume/persistentvolume/util/util.go
  pkg/controller/volume/pvcprotection/pvc_protection_controller.go
  pkg/controller/volume/pvprotection/pv_protection_controller.go
  pkg/controller/volume/pvprotection/pv_protection_controller_test.go
  pkg/controller/volume/scheduling/BUILD
  pkg/controller/volume/scheduling/scheduler_assume_cache.go
  pkg/controller/volume/scheduling/scheduler_assume_cache_test.go
  pkg/controller/volume/scheduling/scheduler_binder.go
  pkg/controller/volume/scheduling/scheduler_binder_test.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/scheduler/algorithm/predicates/csi_volume_predicate.go
  pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go
  pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
  pkg/scheduler/algorithm/predicates/testing_helper.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/volume/util/resize_util.go
  test/integration/scheduler/predicates_test.go
  test/integration/scheduler/preemption_test.go
  test/integration/statefulset/statefulset_test.go
  test/integration/statefulset/util.go
  test/integration/volume/persistent_volumes_test.go
Labels: area/multi-tenancy

#272 fix endpoints cannot get ip/ports issue
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/util.sh
Labels: area/performance-test

#276 multi-tenancy networking: create default network on new tenants
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/tenantcontroller.go
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
  pkg/controller/tenant/BUILD
  pkg/controller/tenant/config/types.go
  pkg/controller/tenant/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  staging/repos_generated.bzl
  staging/src/BUILD
  staging/src/k8s.io/arktos-ext/BUILD
  staging/src/k8s.io/arktos-ext/go.mod
  staging/src/k8s.io/arktos-ext/go.sum
  staging/src/k8s.io/arktos-ext/hack/boilerplate.go.txt
  staging/src/k8s.io/arktos-ext/hack/update-codegen.sh
  staging/src/k8s.io/arktos-ext/hack/verify-codegen.sh
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/BUILD
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/doc.go
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/register.go
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/types.go
  staging/src/k8s.io/arktos-ext/pkg/apis/arktosextensions/v1/zz_generated.deepcopy.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/clientset.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/doc.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/fake/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/fake/clientset_generated.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/fake/doc.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/fake/register.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/scheme/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/scheme/doc.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/scheme/register.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/arktosextensions_client.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/doc.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/fake/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/fake/doc.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/fake/fake_arktosextensions_client.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/fake/fake_network.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/generated_expansion.go
  staging/src/k8s.io/arktos-ext/pkg/generated/clientset/versioned/typed/arktosextensions/v1/network.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/interface.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/v1/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/v1/interface.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/arktosextensions/v1/network.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/factory.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/generic.go
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/internalinterfaces/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  staging/src/k8s.io/arktos-ext/pkg/generated/listers/arktosextensions/v1/BUILD
  staging/src/k8s.io/arktos-ext/pkg/generated/listers/arktosextensions/v1/expansion_generated.go
  staging/src/k8s.io/arktos-ext/pkg/generated/listers/arktosextensions/v1/network.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  vendor/k8s.io/arktos-ext
Labels: area/controller-manager, area/multi-tenancy, area/networking

#280 tenant controller bootstraps cluster role and binding
  pkg/controller/tenant/BUILD
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy_test.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: area/multi-tenancy

#288 improve tenant extraction from x509 cert
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
Labels: area/multi-tenancy

#293 ETCD Data partition design - revision # changes
  docs/design-proposals/etcd/ETCD-Data-Partition-Design.md
Labels: area/scalability

#300 Add support to ETCD revision format changes. See design doc https://g…
  staging/src/k8s.io/apimachinery/pkg/util/diff/BUILD
  staging/src/k8s.io/apimachinery/pkg/util/diff/compare.go
  staging/src/k8s.io/apimachinery/pkg/util/diff/compare_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/BUILD
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
Labels: area/scalability

#304 ETCD data partition design: added automated new ETCD cluster discovery
  docs/design-proposals/etcd/ETCD-Data-Partition-Design.md
Labels: area/scalability, documentation

#302 Add a set of Arktos-CI test mark
  test/e2e/apimachinery/namespace.go
  test/e2e/apimachinery/watch.go
  test/e2e/apps/daemon_set.go
  test/e2e/apps/deployment.go
  test/e2e/apps/job.go
  test/e2e/apps/replica_set.go
  test/e2e/apps/statefulset.go
  test/e2e/common/configmap.go
  test/e2e/common/container_probe.go
  test/e2e/common/pods.go
  test/e2e/common/runtime.go
  test/e2e/common/secrets.go
  test/e2e/kubectl/kubectl.go
  test/e2e/network/networking.go
  test/e2e/network/service.go
  test/e2e/node/events.go
  test/e2e/node/pods.go
Labels: area/cicd

#303 multi-tenancy daemonset
  cluster/images/etcd/migrate/migrate_client.go
  cmd/kubeadm/app/phases/upgrade/staticpods_test.go
  cmd/kubeadm/app/util/etcd/etcd.go
  pkg/controller/daemon/daemon_controller.go
  pkg/controller/daemon/daemon_controller_test.go
  pkg/controller/daemon/update.go
  pkg/controller/daemon/update_test.go
  pkg/controller/daemon/util/daemonset_util.go
  pkg/controller/daemon/util/daemonset_util_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/storage/objectreader.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/api_object_versioner.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/api_object_versioner_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/errors.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/event.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/event_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/healthcheck.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/healthcheck_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/lease_manager.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/logger.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/test_server.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/testing/utils.go
  test/integration/daemonset/daemonset_test.go
  test/integration/framework/etcd.go
  vendor/BUILD
Labels: area/multi-tenancy

#317 Improve aws preset kube-up/kube-down
  aws_kube_params.inc
  cluster/aws/cleanup-preset-vm.sh
  cluster/aws/configure-vm.sh
  cluster/aws/util.sh
Labels: area/cicd

#323 make service controller multi-tenant
  pkg/controller/service/patch.go
  pkg/controller/service/patch_test.go
  pkg/controller/service/service_controller.go
  pkg/controller/service/service_controller_test.go
  pkg/kubelet/dockershim/libdocker/fake_client.go
  pkg/kubelet/kuberuntime/helpers_linux_test.go
  pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go
Labels: In Review, area/multi-tenancy

#287 doc: multi-tenancy network: endpoints design proposal
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
Labels: area/multi-tenancy, area/networking
