Repository CentaurusInfra/arktos, pull requests merged in 2020-12, with the labels that each got.

#817 1.18 improvement api server cacher index and reduce watchers
  pkg/registry/core/action/storage/BUILD
  pkg/registry/core/action/storage/storage.go
  pkg/registry/core/action/strategy.go
  pkg/registry/core/node/storage/BUILD
  pkg/registry/core/node/storage/storage.go
  pkg/registry/core/node/strategy.go
  pkg/registry/core/pod/storage/storage.go
  pkg/registry/core/pod/strategy.go
  pkg/registry/core/secret/storage/BUILD
  pkg/registry/core/secret/storage/storage.go
  pkg/registry/core/secret/strategy.go
  staging/src/k8s.io/apimachinery/pkg/labels/selector.go
  staging/src/k8s.io/apimachinery/pkg/labels/selector_test.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/BUILD
  staging/src/k8s.io/apiserver/pkg/registry/generic/options.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/BUILD
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/storage_decorator.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache_test.go
  staging/src/k8s.io/apiserver/pkg/storage/interfaces.go
  staging/src/k8s.io/apiserver/pkg/storage/selection_predicate.go
  staging/src/k8s.io/apiserver/pkg/storage/util.go
Labels: approved, lgtm, size/XL

#822 1.18 improvement watch memory leak
  hack/arktos_copyright_copied_k8s_files
  staging/src/k8s.io/apimachinery/pkg/runtime/BUILD
  staging/src/k8s.io/apimachinery/pkg/runtime/interfaces.go
  staging/src/k8s.io/apimachinery/pkg/runtime/negotiate.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/watch.go
  staging/src/k8s.io/apiserver/pkg/endpoints/watch_test.go
Labels: approved, lgtm, size/L

#834 1.18 improvement kubelet
  pkg/kubelet/eviction/BUILD
  pkg/kubelet/eviction/eviction_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/nodelease/BUILD
  pkg/kubelet/nodelease/controller.go
  pkg/kubelet/nodelease/controller_test.go
  pkg/kubelet/pod/pod_manager.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/types/pod_update.go
  pkg/kubelet/types/pod_update_test.go
  pkg/kubelet/util/manager/watch_based_manager.go
Labels: approved, lgtm, size/L

#838 config haproxy for scale-out m2
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
  hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
Labels: approved, lgtm, size/L

#837 haproxy setup script
  hack/scale_out_poc/haproxy_1T1R/haproxy.cfg
  hack/scale_out_poc/haproxy_1T1R/setup_haproxy.sh
Labels: approved, lgtm, size/L

#841 convert kubeclient to support multiple tenant partition
  cmd/kubelet/app/server.go
  pkg/kubelet/configmap/configmap_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubemark/hollow_kubelet.go
Labels: approved, lgtm, size/L

#842 backwards compatible node controller
  cmd/kube-controller-manager/app/core.go
  pkg/controller/nodelifecycle/scale_out_poc_util.go
Labels: approved, lgtm, size/M

#839 Pickup changes in M1 branch into M2 branch
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  cmd/kubelet/app/server.go
  cmd/kubemark/hollow-node.go
  hack/scale_out_poc/nginx.conf
  test/kubemark/gce/util.sh
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/M

#847 update nginx.conf
  hack/scale_out_poc/two_TP/nginx.conf
Labels: approved, lgtm, size/L

#848 fix haproxy.cfg
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
Labels: approved, lgtm, size/S

#840 Pick up performance test changes
  cluster/common.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/partitionserver-configure-helper.sh
  cluster/gce/manifests/etcd.manifest
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kubemark/BUILD
  cmd/kubemark/hollow-node.go
  hack/apiserver.config
  hack/lib/common.sh
  pkg/registry/cachesize/cachesize.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
Labels: approved, lgtm, size/M

#850 set up 2T1R kubemark clusters with haproxy dynamic configured
  cluster/common.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/partitionserver-configure-helper.sh
  cluster/gce/util.sh
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
  test/kubemark/gce/util.sh
  test/kubemark/resources/hollow-node_template.yaml
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/L

#851 statefulset fix and kubeclient switch
  cmd/kubelet/app/server.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/reconciler/reconciler.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/volume_manager.go
Labels: approved, lgtm, size/M

#852 Create POC test tenants with kubemark test
  perf-tests/clusterloader2/testing/arktos/tenant1.yaml
  perf-tests/clusterloader2/testing/arktos/tenant2.yaml
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/M

#853 multi-tenancy perf-test
  perf-tests/clusterloader2/pkg/execservice/exec_service.go
  perf-tests/clusterloader2/pkg/framework/client/objects.go
  perf-tests/clusterloader2/pkg/framework/framework.go
  perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
  perf-tests/clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  perf-tests/clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  perf-tests/clusterloader2/pkg/measurement/common/probes/probes.go
  perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
  perf-tests/clusterloader2/pkg/measurement/util/object_store.go
  perf-tests/clusterloader2/pkg/prometheus/prometheus.go
  perf-tests/clusterloader2/pkg/test/simple_test_executor.go
  perf-tests/clusterloader2/pkg/util/multi-tenancy.go
  staging/src/k8s.io/client-go/dynamic/dynamicinformer/informer.go
Labels: approved, lgtm, size/L

#855 Bump k8s.io/klog to v1.0.0
  staging/src/k8s.io/component-base/cli/globalflag/globalflags_test.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#859 set larger haproxy maxconn for scale out tests
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
Labels: approved, lgtm, size/XS

#862 create direct TP kubeconfig in kubemark test
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/S

#863 Append limits.conf to explictly set for root and haproxy
  cluster/gce/util.sh
Labels: approved, lgtm, size/XS

#856 fix kubeclient usage for node access
  pkg/kubelet/kubelet.go
  pkg/kubelet/volumemanager/reconciler/reconciler.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/volume_manager.go
Labels: approved, lgtm, size/S

#857 workaround a pod terminating issue in perf
  pkg/kubelet/kubelet_pods.go
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/S

#864 apply network CRD in TP1/TP2
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/S

#866 haproxy config
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
Labels: approved, lgtm, size/S

#865 cherry pick commits to fix concurrent map error
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
Labels: size/XS

#870 update readme
  README.md
Labels: approved, lgtm, size/XS

#869 Point NPD to Resource master URL instead of proxy
  test/kubemark/resources/hollow-node_template.yaml
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/S

#874 Disable APIServerConfigManager and run update-gofmt
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/core.go
  cmd/kube-proxy/app/server.go
  cmd/kube-scheduler/app/server.go
  cmd/kubelet/app/server.go
  perf-tests/clusterloader2/pkg/util/multi-tenancy.go
  pkg/kubelet/configmap/configmap_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/volume_manager.go
Labels: approved, lgtm, size/M

#875 enable the creation of default network object in kubemark
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/S

#877 fix typo
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/XS

#882 Disable network object creation in kubemark
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/S

#879 enable prometheus for scale-out
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/util.sh
Labels: Verifying, approved, lgtm, size/M

#881 Remove kube-proxy from hollow node pod
  test/kubemark/resources/hollow-node_template.yaml
Labels: approved, lgtm, size/S

#883 Enable prometheus only on tenant & resource masters in scaleout arch
  cluster/gce/gci/configure-helper.sh
  cluster/gce/util.sh
Labels: approved, lgtm, size/S

#885 fix controller QPS issue
  cmd/kube-controller-manager/app/core.go
  pkg/controller/replicaset/replica_set.go
  staging/src/k8s.io/client-go/util/flowcontrol/throttle.go
Labels: approved, lgtm, size/M

#888 Quick fix of handling mirror pod issue
  pkg/kubelet/kubelet.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/types/pod_update.go
Labels: approved, lgtm, size/S

#886 expose haproxy prometheus
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
  hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
Labels: Verifying, approved, lgtm, size/M

#889 fix haproxy failure due to restarting too quickly
  cluster/gce/util.sh
Labels: approved, lgtm, size/XS

#893 remove network CRD and object retrieval for scalability tests
  cluster/gce/gci/configure-helper-common.sh
  pkg/kubelet/network/dns/dns.go
  staging/src/k8s.io/client-go/util/flowcontrol/throttle.go
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/M

#894 fix mizar-controller name typo
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/XS

#895 fix the haproxy crash after patching for prometheus
  cluster/gce/util.sh
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
Labels: approved, lgtm, size/S

#896 fix haproxy cfg & script to work in one-box
  cluster/gce/util.sh
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
  hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
Labels: approved, lgtm, size/M

#899 enlarge net.netfilter.nf_conntrack_max when building scale-out masters
  cluster/gce/util.sh
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/XS

#902 Multi TP Test Cluster Creation
  cluster/gce/util.sh
  hack/BUILD
  hack/scale_out_poc/config_haproxy/cfg_generator/BUILD
  hack/scale_out_poc/config_haproxy/cfg_generator/cfg_generator.go
  hack/scale_out_poc/config_haproxy/cfg_generator/util.go
  hack/scale_out_poc/config_haproxy/haproxy.cfg.template
  hack/scale_out_poc/config_haproxy/setup_haproxy.sh
  test/kubemark/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/XL
