Repository CentaurusInfra/arktos, pull requests merged in 2020-03, with the labels that each got.

#99 extract tenant from x509 cert
  hack/lib/util.sh
  pkg/apis/authentication/v1/zz_generated.conversion.go
  pkg/apis/authentication/v1beta1/zz_generated.conversion.go
  staging/src/k8s.io/api/authentication/v1/generated.proto
  staging/src/k8s.io/api/authentication/v1beta1/generated.proto
  staging/src/k8s.io/apiserver/pkg/audit/event/attributes.go
  staging/src/k8s.io/apiserver/pkg/authentication/group/authenticated_group_adder.go
  staging/src/k8s.io/apiserver/pkg/authentication/request/anonymous/anonymous.go
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
  staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/authorization.go
  test/integration/apiserver/apiserver_partition_test.go
Labels: area/multi-tenancy

#101 Update design documents for multi-tenancy feature
  docs/design-proposals/apiserver/multi-tenancy.md
  docs/design-proposals/multi-tenancy/images/multi-tenancy-overview1.gliffy
  docs/design-proposals/multi-tenancy/images/multi-tenancy-overview1.png
  docs/design-proposals/multi-tenancy/images/multi-tenancy-overview2.gliffy
  docs/design-proposals/multi-tenancy/images/multi-tenancy-overview2.png
  docs/design-proposals/multi-tenancy/multi-tenancy-access-control.md
  docs/design-proposals/multi-tenancy/multi-tenancy-api-resource-model.md
  docs/design-proposals/multi-tenancy/multi-tenancy-network.md
  docs/design-proposals/multi-tenancy/multi-tenancy-overview.md
  docs/design-proposals/multi-tenancy/multi-tenancy-schduler-agent-and-controllers.md
Labels: area/multi-tenancy

#119 Revert resource version initialization in ListAndWatch due to performance issue.
  cmd/kube-scheduler/app/options/options_test.go
  cmd/kubelet/app/server_bootstrap_test.go
  hack/lib/etcd.sh
  staging/src/k8s.io/api/core/v1/generated.pb.go
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
  staging/src/k8s.io/client-go/tools/cache/reflector.go
  test/integration/apiserver/apiserver_partition_test.go
  test/integration/workloadcontrollermanager/multi_config_test.go
Labels: area/scalability, bug

#117 Multi tenancy/cluster role scope
  pkg/apis/rbac/validation/validation.go
  pkg/apis/rbac/validation/validation_test.go
  pkg/controller/clusterroleaggregation/clusterroleaggregation_controller_test.go
  pkg/registry/rbac/clusterrole/policybased/storage.go
  pkg/registry/rbac/clusterrole/policybased/storage_test.go
  pkg/registry/rbac/clusterrole/strategy.go
  pkg/registry/rbac/clusterrole/strategy_test.go
  pkg/registry/rbac/clusterrolebinding/policybased/storage.go
  pkg/registry/rbac/clusterrolebinding/strategy.go
  pkg/registry/rbac/clusterrolebinding/strategy_test.go
  staging/src/k8s.io/api/rbac/v1/types.go
  staging/src/k8s.io/api/rbac/v1alpha1/types.go
  staging/src/k8s.io/api/rbac/v1beta1/types.go
  staging/src/k8s.io/client-go/informers/rbac/v1/clusterrole.go
  staging/src/k8s.io/client-go/informers/rbac/v1/interface.go
  staging/src/k8s.io/client-go/informers/rbac/v1alpha1/clusterrole.go
  staging/src/k8s.io/client-go/informers/rbac/v1alpha1/interface.go
  staging/src/k8s.io/client-go/informers/rbac/v1beta1/clusterrole.go
  staging/src/k8s.io/client-go/informers/rbac/v1beta1/interface.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1/clusterrole.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1/fake/fake_clusterrole.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1/fake/fake_rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1/rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1/clusterrole.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1/fake/fake_clusterrole.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1/fake/fake_rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1/rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1beta1/clusterrole.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1beta1/fake/fake_clusterrole.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1beta1/fake/fake_rbac_client.go
  staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1beta1/rbac_client.go
  staging/src/k8s.io/client-go/listers/rbac/v1/clusterrole.go
  staging/src/k8s.io/client-go/listers/rbac/v1/expansion_generated.go
  staging/src/k8s.io/client-go/listers/rbac/v1alpha1/clusterrole.go
  staging/src/k8s.io/client-go/listers/rbac/v1alpha1/expansion_generated.go
  staging/src/k8s.io/client-go/listers/rbac/v1beta1/clusterrole.go
  staging/src/k8s.io/client-go/listers/rbac/v1beta1/expansion_generated.go
  test/integration/etcd/multi_tenancy_data.go
Labels: area/multi-tenancy

#30 Add design spec for partial runtime support
  docs/design-proposals/node/Partial-Runtime-Readiness-Handling.md
  docs/design-proposals/node/Pod-dependency-cross-workload-types.PNG
Labels: area/unified-vm-container

#124 Add tenant controller
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/BUILD
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-controller-manager/app/options/options_test.go
  cmd/kube-controller-manager/app/options/tenantcontroller.go
  pkg/apis/authorization/v1/zz_generated.conversion.go
  pkg/apis/authorization/v1beta1/zz_generated.conversion.go
  pkg/controller/BUILD
  pkg/controller/apis/config/BUILD
  pkg/controller/apis/config/types.go
  pkg/controller/apis/config/v1alpha1/BUILD
  pkg/controller/apis/config/v1alpha1/defaults.go
  pkg/controller/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/tenant/BUILD
  pkg/controller/tenant/config/BUILD
  pkg/controller/tenant/config/doc.go
  pkg/controller/tenant/config/types.go
  pkg/controller/tenant/config/v1alpha1/BUILD
  pkg/controller/tenant/config/v1alpha1/conversion.go
  pkg/controller/tenant/config/v1alpha1/defaults.go
  pkg/controller/tenant/config/v1alpha1/doc.go
  pkg/controller/tenant/config/v1alpha1/register.go
  pkg/controller/tenant/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/tenant/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tenant/config/zz_generated.deepcopy.go
  pkg/controller/tenant/doc.go
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  pkg/registry/rbac/clusterrolebinding/registry.go
  pkg/registry/rbac/rolebinding/registry.go
  pkg/registry/rbac/validation/rule.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
  plugin/pkg/auth/authorizer/rbac/rbac.go
  staging/src/k8s.io/api/authorization/v1/generated.proto
  staging/src/k8s.io/api/authorization/v1/types.go
  staging/src/k8s.io/api/authorization/v1/types_swagger_doc_generated.go
  staging/src/k8s.io/api/authorization/v1beta1/generated.proto
  staging/src/k8s.io/api/authorization/v1beta1/types.go
  staging/src/k8s.io/api/authorization/v1beta1/types_swagger_doc_generated.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
  staging/src/k8s.io/metrics/pkg/apis/custom_metrics/v1beta2/zz_generated.conversion.go
  test/integration/framework/master_utils.go
Labels: area/multi-tenancy

#136 fix make upadte issue with zz_generated.conversion.go
  pkg/controller/apis/config/v1alpha1/doc.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
Labels: bug

#129 extract tenant from bearer token file
  hack/testdata/auth-tokens.csv
  staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/BUILD
  staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/tokenfile.go
  staging/src/k8s.io/apiserver/pkg/authentication/token/tokenfile/tokenfile_test.go
Labels: area/multi-tenancy

#148 add tenant extraction from basic auth token file
  pkg/master/reconcilers/mastercount.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/BUILD
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/passwordfile.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/passwordfile_test.go
Labels: area/multi-tenancy

#150 add public ip support to arktos-up.sh
  hack/arktos-up.sh
Labels: area/multi-tenancy, area/project-infra

#145 add tenant to JWT bearer token authentication
  pkg/kubeapiserver/authenticator/config.go
  pkg/serviceaccount/jwt.go
  pkg/serviceaccount/jwt_test.go
  pkg/serviceaccount/legacy.go
  pkg/serviceaccount/util.go
  pkg/serviceaccount/util_test.go
  plugin/pkg/admission/security/podsecuritypolicy/admission.go
Labels: area/multi-tenancy

#153 removed color from kata-setup output
  hack/install-kata.sh
Labels: enhancement
