Repository CentaurusInfra/arktos, pull requests merged in 2020-02, with the labels that each got.

#44 Refactor apiserver parition integration tests + go fmt
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  test/integration/apiserver/apiserver_partition_test.go
  test/integration/framework/master_utils.go
Labels: scalability

#46 Integration tests for api server partition
  test/integration/apiserver/apiserver_partition_test.go
Labels: scalability

#31 Minor grammatical changes for better clarity in the design document
  docs/design-proposals/node/Support-multiple-runtimes.md
Labels: area/unified-vm-container

#54 Added kube config files to kubelet and kube proxy
  cmd/kube-proxy/app/server.go
  cmd/kubelet/app/options/options.go
  cmd/kubelet/app/options/options_test.go
Labels: scalability

#51 Fix aggregate watch left over in e2e tests.
  hack/make-rules/update.sh
  staging/src/k8s.io/apimachinery/pkg/watch/watch.go
  staging/src/k8s.io/client-go/tools/cache/reflector.go
  staging/src/k8s.io/client-go/tools/clientcmd/loader_test.go
  test/e2e_node/apparmor_test.go
  test/e2e_node/density_test.go
  test/integration/apiserver/apiserver_partition_test.go
  test/integration/workloadcontrollermanager/main_test.go
Labels: area/scalability
