Repository CentaurusInfra/arktos, pull requests merged in 2021-07, with the labels that each got.

#1109 design doc: DaemonSet support in scale-out Arktos
  docs/design-proposals/arch/arktos_scale_out.md
  docs/design-proposals/arch/daemonset.md
  docs/design-proposals/arch/images/daemonset_OPD/daemonset-support-DS-creating-DSadding.jpg
  docs/design-proposals/arch/images/daemonset_OPD/daemonset-support-DS-creating-podStarting-envPreparing.jpg
Labels: approved, lgtm, size/M

#1113 kubemark cluster starts partition servers in parallel
  cluster/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/L

#1118 logging change to investigate extra GET calls
  pkg/kubelet/status/status_manager.go
Labels: lgtm, size/XS

#1120 Fix a bug that event client was created with wrong user agent
  cmd/kube-scheduler/app/options/options.go
Labels: approved, bug, lgtm, size/XS

#1130 bug fix: unable to delete pods at hollow nodes
  cmd/kubemark/hollow-node.go
Labels: lgtm, size/XS
