Repository CentaurusInfra/arktos, pull requests merged in 2021-09, with the labels that each got.

#1125 Set user agent for clients when talking to api servers in the partition
  cmd/kube-controller-manager/app/config/config.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-scheduler/app/options/options.go
  cmd/kubelet/app/server.go
  cmd/kubemark/hollow-node.go
  pkg/controller/util/node/controller_utils.go
  staging/src/k8s.io/client-go/util/clientutil/clientutil.go
  staging/src/k8s.io/client-go/util/clientutil/clientutil_test.go
Labels: size/L, lgtm

#1169 Add label name indexer to pod
  perf-tests/clusterloader2/pkg/imagepreload/BUILD
  perf-tests/clusterloader2/pkg/measurement/common/BUILD
  perf-tests/clusterloader2/pkg/measurement/common/scheduling_throughput.go
  perf-tests/clusterloader2/pkg/measurement/common/slos/BUILD
  perf-tests/clusterloader2/pkg/measurement/util/informer/BUILD
  perf-tests/clusterloader2/pkg/measurement/util/object_store.go
  perf-tests/clusterloader2/pkg/measurement/util/wait_for_pods.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  test/e2e/framework/perf_util.go
Labels: size/L

#835 Reduce kubelet getting node
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_node_status_test.go
Labels: area/scalability, size/L, approved, lgtm

#1179 Send fake bookmark event to client to reduce size of initEvents
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
Labels: size/S, lgtm

#1183 Send fake bookmark event to client to reduce size of initEvents
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
Labels: area/scalability, size/S, approved, lgtm

#1184 PR 96117 - Disable watchcache for events 1.18
  pkg/registry/cachesize/cachesize.go
Labels: size/XS, approved, lgtm

#1188 Update Etcd to 3.4.3
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd-empty-dir-cleanup/Makefile
  cluster/images/etcd/Makefile
  cluster/images/etcd/README.md
  cluster/images/etcd/migrate-if-needed.sh
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/constants/constants_test.go
  hack/install-etcd.sh
  hack/lib/etcd.sh
  vendor/go.etcd.io/etcd/version/version.go
Labels: size/M, approved, lgtm

#1173 porting changes from community issue 77733 (#1151)
  pkg/controller/nodelifecycle/BUILD
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/util/node/BUILD
  pkg/controller/util/node/controller_utils.go
Labels: size/XXL, approved, lgtm

#1172 scale-out: kube-proxy connects to multiple TPs and arranges service/endpoint in tenant aware way
  cmd/kube-proxy/app/BUILD
  cmd/kube-proxy/app/server.go
  cmd/kube-proxy/app/server_others.go
  hack/lib/common.sh
  pkg/kubemark/hollow_proxy.go
  pkg/proxy/apis/config/types.go
  pkg/proxy/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/proxy/endpoints.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/ipvs/proxier.go
  pkg/proxy/service.go
  pkg/proxy/userspace/proxier.go
  pkg/proxy/userspace/roundrobin.go
  staging/src/k8s.io/kube-proxy/config/v1alpha1/types.go
Labels: size/L, approved, lgtm

#1174 adds deployment network admission controller to enforce network label in deployment spec
  cmd/arktos-network-controller/app/dns_deployment.go
  pkg/kubeapiserver/options/BUILD
  pkg/kubeapiserver/options/plugins.go
  plugin/BUILD
  plugin/pkg/admission/deployment/network/BUILD
  plugin/pkg/admission/deployment/network/admission.go
Labels: size/M, approved, lgtm

#1177 arktos-network-controller introduces arg to make names of resources it creates not fully hardcoded
  cmd/arktos-network-controller/app/controller.go
  cmd/arktos-network-controller/app/controller_test.go
  cmd/arktos-network-controller/app/dns_deployment.go
  cmd/arktos-network-controller/app/dns_deployment_test.go
  cmd/arktos-network-controller/network-controller.go
Labels: size/M, approved, lgtm

#1186 Pick up 930 fix in role for node-impam-controller
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: size/M, approved, lgtm

#1185 Update apiserver for large-scale cluster: target-ram-mb, max_request_inflight,max_mutating_request_inflight
  cluster/gce/gci/configure-helper-common.sh
Labels: size/S, approved, lgtm

#1181 This PR is to fix both issue #1180 and issue #1140 after consolidating with PR1176
  hack/arktos-worker-up.sh
  hack/lib/common-var-init.sh
  hack/lib/common.sh
  pkg/kubelet/BUILD
  pkg/kubelet/kubeclientmanager/kubeclient_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters_test.go
  pkg/kubelet/kubelet_node_status_test.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_pods_linux_test.go
  pkg/kubelet/kubelet_pods_test.go
  pkg/kubelet/kubelet_resources_test.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/kubelet_volumes_linux_test.go
  pkg/kubelet/kubelet_volumes_test.go
  pkg/kubelet/network/dns/BUILD
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/network/dns/dns_test.go
Labels: size/XXL, approved, lgtm

#1190 scale-up.sh enables network service support by default
  hack/arktos-up.sh
  hack/lib/common.sh
  hack/testdata/default-flat-network.tmpl
Labels: size/M, approved, lgtm

#1191 scale-up.sh: able to install flannel cni plugin
  hack/arktos-cni.rc
  hack/arktos-up.sh
Labels: size/M, approved, lgtm

#1198 Issue#1189: changes in arktos-up-scale-out-poc.sh for automation of local dev 1X1 scale-out setup
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
Labels: size/M, approved, lgtm

#1187 Perf test reduce listpods
  perf-tests/clusterloader2/pkg/imagepreload/BUILD
  perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
  perf-tests/clusterloader2/pkg/measurement/common/BUILD
  perf-tests/clusterloader2/pkg/measurement/common/scheduling_throughput.go
  perf-tests/clusterloader2/pkg/measurement/common/service_creation_latency.go
  perf-tests/clusterloader2/pkg/measurement/common/slos/BUILD
  perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  perf-tests/clusterloader2/pkg/measurement/util/informer/BUILD
  perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
  perf-tests/clusterloader2/pkg/measurement/util/object_store.go
  perf-tests/clusterloader2/pkg/measurement/util/selector.go
  perf-tests/clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: size/L

#1199 arktos-up-scale-out-poc.sh to start 2x2 scale-out cluster with service support enabled
  docs/setup-guide/scale-out-local-dev-setup.md
  hack/arktos-cni.rc
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
Labels: size/M, approved, lgtm

#1203 ensure resolv.conf for Ubuntu 16.04
  hack/lib/common-var-init.sh
Labels: size/S, approved, lgtm
