Repository CentaurusInfra/arktos, pull requests merged in 2021-06, with the labels that each got.

#1092 Pick up recent perf test changes
  cluster/gce/gci/configure.sh
  pkg/scheduler/eventhandlers.go
  pkg/scheduler/scheduler.go
Labels: size/S

#1103 fix prometheus config to include haproxy metrics
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/XS

#1105 Decouple proxy operations from kube-up and create-master functions and optimize proxy creation routines
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  cluster/proxy-down.sh
  cluster/proxy-up.sh
  cluster/skeleton/util.sh
  test/kubemark/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/L

#1107 Add perf log to perf test and controller manager
  perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  pkg/controller/job/job_controller.go
Labels: lgtm, size/M

#1108 set user agent for hollow nodes and perf test clients
  cmd/kubemark/hollow-node.go
  perf-tests/clusterloader2/pkg/framework/multiclient.go
Labels: size/S

#1110 ETCD3.4.3
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd-empty-dir-cleanup/Makefile
  cluster/images/etcd/Makefile
  cluster/images/etcd/README.md
  cluster/images/etcd/migrate-if-needed.sh
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/constants/constants_test.go
  hack/install-etcd.sh
  hack/lib/etcd.sh
  vendor/go.etcd.io/etcd/version/version.go
Labels: size/M
