Repository CentaurusInfra/arktos, pull requests merged in 2021-12, with the labels that each got.

#1232 COS-93, Ubuntu 18.04 support with Mizar as static pods in scaleout architecture
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/util.sh
  cluster/get-kube-binaries.sh
Labels: size/L

#1237 Bug fix for mizar-arktos network controller watch/update arktos network objects
  cmd/kube-controller-manager/app/mizarcontrollers.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
Labels: size/S

#1210 revisted daemonset design, added kube-proxy related change
  docs/design-proposals/arch/daemonset.md
  docs/design-proposals/arch/images/daemonset_OPD/kube-proxy-svc-ep-manage.jpg
Labels: size/M, approved, lgtm

#1238 Bug fix for mizar-arktos network controller watch/update arktos network objects
  cmd/kube-controller-manager/app/mizarcontrollers.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: size/M, approved, lgtm

#1239 Simplify worker up
  hack/arktos-worker-up.sh
Labels: size/M

#1245 Remove APIServerConfigManager usage from KCM - not currently used - does not work well with scale out
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/controllermanager.go
Labels: size/S, approved, lgtm

#1240 Scale out Mizar integration 1x1
  cmd/kube-controller-manager/app/controllermanager.go
  hack/arktos-up-scale-out-poc.sh
  hack/arktos-worker-up.sh
Labels: size/M, lgtm

#1242 Code structure - Openstack request support, single vm creation/delete/get
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apimachinery/pkg/runtime/schema/interfaces.go
  staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go
  staging/src/k8s.io/apiserver/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/response.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/routes/BUILD
  staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/BUILD
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackRequestTemplate.json
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  test/e2e/arktos/testvm.json
Labels: size/L

#1250 Kube proxy multi tenant scaleout
  cmd/kube-proxy/app/server.go
  pkg/kubemark/hollow_proxy.go
  pkg/proxy/config/api_test.go
  pkg/proxy/config/config.go
  pkg/proxy/config/config_test.go
  pkg/proxy/endpoints.go
  pkg/proxy/endpoints_test.go
  pkg/proxy/healthcheck/healthcheck.go
  pkg/proxy/healthcheck/healthcheck_test.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
  pkg/proxy/ipvs/proxier.go
  pkg/proxy/ipvs/proxier_test.go
  pkg/proxy/service.go
  pkg/proxy/service_test.go
  pkg/proxy/types.go
  pkg/proxy/userspace/proxier.go
  pkg/proxy/userspace/proxier_test.go
  pkg/proxy/userspace/roundrobin.go
  pkg/proxy/userspace/roundrobin_test.go
  pkg/proxy/util/utils.go
  pkg/proxy/util/utils_test.go
  pkg/proxy/winuserspace/proxier.go
  pkg/proxy/winuserspace/proxier_test.go
  pkg/proxy/winuserspace/proxysocket.go
  pkg/proxy/winuserspace/roundrobin.go
  pkg/proxy/winuserspace/roundrobin_test.go
  pkg/proxy/winuserspace/types.go
  staging/src/k8s.io/apimachinery/pkg/types/namespacedname.go
Labels: size/XXL

#1249 Use VM name from the request and essential UT for the utility function
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackRequestTemplate.json
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
  test/e2e/arktos/testvm.json
Labels: size/L

#1254 Use explicitly set request context in action creation
  pkg/registry/core/pod/storage/BUILD
  pkg/registry/core/pod/storage/storage.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go
Labels: size/M, approved, lgtm

#1255 Cherry-pick: Use explicitly set request context in action creation (#1254)
  pkg/registry/core/pod/storage/BUILD
  pkg/registry/core/pod/storage/storage.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go
Labels: size/M, lgtm

#1258 Bug fix for kubelet service lister: use different service indexer for different TP
  pkg/kubelet/kubelet.go
Labels: size/XS, lgtm

#1257 Bug fix for kubelet service lister: use different service indexer for different TP
  pkg/kubelet/kubelet.go
Labels: size/XS, lgtm
