Repository CentaurusInfra/arktos, pull requests merged in 2021-04, with the labels that each got.

#1058 fix rp server failed to collect pprof error
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/partitionserver-configure-helper.sh
Labels: approved, lgtm, size/M

#1066 fix rp server failed to collect pprof error (#1058)
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/partitionserver-configure-helper.sh
Labels: lgtm, size/M

#1062 Fix issue #1039 and #1046
  cluster/gce/gci/configure-helper-common.sh
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
Labels: approved, lgtm, size/S

#1069 debug logging for scheduler perf analysis
  pkg/scheduler/algorithm/predicates/metadata.go
  pkg/scheduler/algorithm/priorities/interpod_affinity.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/eventhandlers.go
  pkg/scheduler/internal/cache/cache.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/scheduler.go
Labels: lgtm, size/M

#1070 Add log for percentageOfNodesToScore vs. evaluated node
  pkg/scheduler/core/generic_scheduler.go
Labels: lgtm, size/XS

#1073 update hollow-node timeout to 20/sec plus additional 15 minutes
  test/kubemark/start-kubemark.sh
Labels: lgtm, size/XS

#1074 reduce log entries for informational logs
  pkg/scheduler/algorithm/predicates/metadata.go
  pkg/scheduler/algorithm/priorities/interpod_affinity.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/eventhandlers.go
  pkg/scheduler/internal/cache/cache.go
Labels: lgtm, size/S

#1072 Force setting nodes to be evaluated as 500.
  pkg/scheduler/core/generic_scheduler.go
Labels: do-not-merge, lgtm, size/XS

#1075 fix UT that missed in PR 1062
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Labels: lgtm, size/S

#1040 fix issue 1038. kubeconfig for kcm on TP to use the proxy till the KCM supports direct talk to RPs
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
  test/kubemark/start-kubemark.sh
Labels: lgtm, size/M

#1076 kube-sched: perf-related back-ports: Merge pull request #86046 from ahg-g/ahg1-affinity
  pkg/scheduler/algorithm/predicates/metadata.go
  pkg/scheduler/algorithm/predicates/metadata_test.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/testing_helper.go
  pkg/scheduler/core/generic_scheduler.go
Labels: WIP, size/XL

#1071 kube-sched: perf-related back-ports: Merge pull request #85862 from ahg-g/ahg-antiAffinity
  pkg/scheduler/algorithm/predicates/metadata.go
Labels: WIP, approved, size/S

#1080 Adding mizar network policy controller
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/builtins.pb.go
  pkg/controller/mizar/builtins.proto
  pkg/controller/mizar/grpc_adaptor.go
  pkg/controller/mizar/grpc_adaptor_mock.go
  pkg/controller/mizar/mizar-network-policy-controller.go
  pkg/controller/mizar/util.go
Labels: approved, lgtm, size/XXL
