Repository CentaurusInfra/arktos, pull requests merged in 2021-01, with the labels that each got.

#897 Extend kubelet to use kubeclient from more than 2 tenant partitions
  pkg/kubelet/config/config.go
  pkg/kubelet/configmap/configmap_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/util/util.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
Labels: approved, lgtm, size/L

#901 Disable windows build - not supported in arktos
  build/build-image/cross/Dockerfile
  hack/lib/golang.sh
  pkg/kubelet/cm/cgroup_manager_unsupported.go
  pkg/kubelet/cm/helpers_unsupported.go
  pkg/kubelet/kuberuntime/helpers_unsupported.go
  pkg/kubelet/kuberuntime/kuberuntime_container_unsupported.go
Labels: approved, lgtm, size/M

#900 Add generic extra args capability to apiserver, controller, scheduler configuration
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/S

#907 Debug logging in kubelet and scheduler
  pkg/kubelet/kubelet_pods.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/internal/cache/cache.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/S

#906 separate and direct haproxy and add scheduler & controller prometheus
  cluster/gce/gci/configure-helper-common.sh
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
  hack/scale_out_poc/haproxy_2T1R/setup_haproxy.sh
Labels: approved, lgtm, size/M

#910 log proxy entry asap when the request is received
  hack/scale_out_poc/config_haproxy/haproxy.cfg.template
  hack/scale_out_poc/haproxy_2T1R/haproxy.cfg
Labels: approved, lgtm, size/XS

#909 fix mholt/caddy reference issue
  go.mod
  staging/src/k8s.io/apimachinery/go.mod
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cluster-bootstrap/go.mod
  staging/src/k8s.io/code-generator/go.mod
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/cri-api/go.mod
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/node-api/go.mod
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-controller/go.mod
Labels: approved, lgtm, size/M

#911 make haproxy dump logs only to /var/log/haproxy.log (part 2)
  cluster/gce/util.sh
  hack/scale_out_poc/config_haproxy/haproxy.cfg.template
  hack/scale_out_poc/config_haproxy/setup_haproxy.sh
Labels: approved, lgtm, size/M

#908 fix onebox haproxy cfg script
  hack/scale_out_poc/config_haproxy/setup_haproxy.sh
Labels: approved, lgtm, size/XS

#912 Settings of max-request-inflight and max-mutating-request-inflight, cap api server mem usage for 600G
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
Labels: approved, lgtm, size/M

#913 bug fix
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/XS

#915 fix issue with invalid cmd/synctax
  cluster/gce/gci/configure-helper-common.sh
Labels: approved, lgtm, size/XS

#916 set wait period per hollow-node #
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/S

#918 Fix cross tenant gather
  perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
  perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Labels: approved, lgtm, size/XS

#926 1.18 kubelet patch status reduce
  build/workspace.bzl
  cluster/addons/node-problem-detector/npd.yaml
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure.sh
  hack/arktos_copyright_copied_k8s_files
  pkg/kubelet/apis/config/v1beta1/defaults.go
  pkg/kubemark/hollow_kubelet.go
  test/e2e/node/node_problem_detector.go
  test/kubemark/resources/hollow-node_template.yaml
Labels: approved, lgtm, size/M

#928 Update README with the new golang version support and community meeting info
  README.md
Labels: approved, lgtm, size/XS

#925 migrate multi-tenancy perf-test to master branch
  perf-tests/clusterloader2/pkg/chaos/nodes.go
  perf-tests/clusterloader2/pkg/execservice/BUILD
  perf-tests/clusterloader2/pkg/execservice/exec_service.go
  perf-tests/clusterloader2/pkg/framework/client/objects.go
  perf-tests/clusterloader2/pkg/framework/framework.go
  perf-tests/clusterloader2/pkg/imagepreload/BUILD
  perf-tests/clusterloader2/pkg/imagepreload/imagepreload.go
  perf-tests/clusterloader2/pkg/measurement/common/bundle/BUILD
  perf-tests/clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  perf-tests/clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  perf-tests/clusterloader2/pkg/measurement/common/probes/probes.go
  perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  perf-tests/clusterloader2/pkg/measurement/util/informer/BUILD
  perf-tests/clusterloader2/pkg/measurement/util/informer/informer.go
  perf-tests/clusterloader2/pkg/measurement/util/object_store.go
  perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/BUILD
  perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  perf-tests/clusterloader2/pkg/prometheus/experimental.go
  perf-tests/clusterloader2/pkg/prometheus/prometheus.go
  perf-tests/clusterloader2/pkg/test/simple_test_executor.go
  perf-tests/clusterloader2/pkg/util/BUILD
  perf-tests/clusterloader2/pkg/util/multi-tenancy.go
  staging/src/k8s.io/client-go/dynamic/dynamicinformer/informer.go
Labels: approved, lgtm, size/L

#934 various changes for scale-out (1st of many more)
  cmd/kubelet/app/options/options.go
  cmd/kubelet/app/server.go
  hack/setup-dev-node.sh
  pkg/kubelet/kubelet.go
Labels: approved, lgtm, size/M

#936 fix backcompat issue in hollow-node
  cmd/kubemark/hollow-node.go
Labels: approved, lgtm, size/XS

#933 migrate the code change about network CRD to master
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/network/dns/dns_test.go
Labels: approved, lgtm, size/XS

#937 fix for pv & pvc with multi-tenancy
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/kubelet/kubelet_pods.go
Labels: approved, lgtm, size/XS

#929 migrate haproxy cfg tool/script to master branch
  cmd/BUILD
  cmd/haproxy-cfg-generator/BUILD
  cmd/haproxy-cfg-generator/cfg_generator.go
  cmd/haproxy-cfg-generator/cfg_generator_test.go
  cmd/haproxy-cfg-generator/data/haproxy.cfg.template
  cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/util.go
  hack/scalability/setup_haproxy.sh
Labels: approved, lgtm, size/XXL

#940 reduce the reset-uuid message log level to 3
  staging/src/k8s.io/apiserver/pkg/registry/rest/meta.go
Labels: approved, lgtm, size/XS

#932 Scaleout node controller to master branch
  api/api-rules/violation_exceptions.list
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/nodelifecyclecontroller.go
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/BUILD
  pkg/controller/nodelifecycle/config/types.go
  pkg/controller/nodelifecycle/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/nodelifecycle/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/BUILD
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/controller/util/node/BUILD
  pkg/controller/util/node/controller_utils.go
  pkg/controller/util/node/controller_utils_test.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
  test/integration/scheduler/BUILD
  test/integration/scheduler/taint_test.go
Labels: approved, lgtm, size/XL

#943 Revert "Scaleout node controller to master branch"
  api/api-rules/violation_exceptions.list
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/nodelifecyclecontroller.go
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/BUILD
  pkg/controller/nodelifecycle/config/types.go
  pkg/controller/nodelifecycle/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/nodelifecycle/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/BUILD
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/controller/util/node/BUILD
  pkg/controller/util/node/controller_utils.go
  pkg/controller/util/node/controller_utils_test.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
  test/integration/scheduler/BUILD
  test/integration/scheduler/taint_test.go
Labels: approved, lgtm, size/XL

#944 Migrate node controller
  api/api-rules/violation_exceptions.list
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/nodelifecyclecontroller.go
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/BUILD
  pkg/controller/nodelifecycle/config/types.go
  pkg/controller/nodelifecycle/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/nodelifecycle/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/BUILD
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/nodelifecycle/scheduler/timed_workers.go
  pkg/controller/nodelifecycle/scheduler/timed_workers_test.go
  pkg/controller/util/node/BUILD
  pkg/controller/util/node/controller_utils.go
  pkg/controller/util/node/controller_utils_test.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
  test/integration/scheduler/BUILD
  test/integration/scheduler/taint_test.go
Labels: approved, lgtm, size/XL

#858 1.18 improvement apiserver connection to etcd
  hack/arktos_copyright_copied_k8s_files
  staging/src/k8s.io/apiextensions-apiserver/test/integration/BUILD
  staging/src/k8s.io/apiextensions-apiserver/test/integration/objectmeta_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/pruning_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/storage/BUILD
  staging/src/k8s.io/apiextensions-apiserver/test/integration/storage/objectreader.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service.go
Labels: approved, lgtm, size/M

#942 add kubeclient manager for scale-out
  cmd/kubelet/app/BUILD
  cmd/kubelet/app/server.go
  hack/arktos-up.sh
  pkg/kubelet/BUILD
  pkg/kubelet/config/BUILD
  pkg/kubelet/config/config.go
  pkg/kubelet/kubeclientmanager/BUILD
  pkg/kubelet/kubeclientmanager/kubeclient_manager.go
  pkg/kubelet/kubeclientmanager/kubeclient_manager_test.go
  pkg/kubelet/kubelet.go
Labels: approved, lgtm, size/L

#948 add usage to kubeclient manager
  pkg/kubelet/BUILD
  pkg/kubelet/configmap/BUILD
  pkg/kubelet/configmap/configmap_manager.go
  pkg/kubelet/kubeclientmanager/kubeclient_manager_test.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/pod/mirror_client_test.go
  pkg/kubelet/prober/BUILD
  pkg/kubelet/prober/common_test.go
  pkg/kubelet/prober/worker_test.go
  pkg/kubelet/secret/BUILD
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/status/BUILD
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/types/pod_update.go
  pkg/kubelet/types/pod_update_test.go
  pkg/kubelet/volumemanager/populator/BUILD
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/volume_manager_test.go
Labels: approved, lgtm, size/L

#951 migrate volume related changes from scale-out poc
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/volumemanager/BUILD
  pkg/kubelet/volumemanager/populator/BUILD
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/volume_manager.go
  pkg/kubelet/volumemanager/volume_manager_test.go
Labels: approved, lgtm, size/M

#945 Initial code merging kube-up & start-kubemark from scale-out-poc to master
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/util.sh
  cluster/validate-cluster.sh
  test/kubemark/gce/util.sh
  test/kubemark/resources/hollow-node_template_scaleout.yaml
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/XXL

#946 1.18 Goaway changes
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/controller-manager/app/serve.go
  cmd/kube-apiserver/app/aggregator.go
  cmd/kube-apiserver/app/testing/BUILD
  cmd/kube-apiserver/app/testing/testserver.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-scheduler/app/server.go
  cmd/workload-controller-manager/app/controllermanager.go
  cmd/workload-controller-manager/app/serve.go
  hack/arktos_copyright_copied_k8s_files
  pkg/master/master.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
  staging/src/k8s.io/apiserver/pkg/server/BUILD
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/server/filters/goaway.go
  staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  staging/src/k8s.io/apiserver/pkg/server/healthz.go
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz_test.go
  staging/src/k8s.io/apiserver/pkg/server/hooks.go
  staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
  staging/src/k8s.io/apiserver/pkg/server/options/server_run_options_test.go
  staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
  test/integration/master/kube_apiserver_test.go
Labels: approved, lgtm, size/XL

#955 kubemark changes for kubelet scale-out migrated code
  cmd/kubemark/BUILD
  cmd/kubemark/hollow-node.go
  pkg/kubemark/hollow_kubelet.go
Labels: approved, lgtm, size/M

#953 fix QPS issue in insecure mode
  pkg/cloudfabric-controller/client_builder.go
  pkg/controller/client_builder.go
Labels: approved, lgtm, size/XS

#949 Master 822 missing cherry pick apiserver
  hack/.golint_failures
  hack/arktos_copyright_copied_k8s_files
  pkg/client/tests/remotecommand_test.go
  pkg/kubectl/cmd/attach/attach_test.go
  pkg/kubectl/cmd/auth/cani_test.go
  pkg/kubectl/cmd/cp/cp_test.go
  pkg/kubectl/cmd/create/create_clusterrolebinding_test.go
  pkg/kubectl/cmd/create/create_configmap_test.go
  pkg/kubectl/cmd/create/create_deployment_test.go
  pkg/kubectl/cmd/create/create_namespace_test.go
  pkg/kubectl/cmd/create/create_pdb_test.go
  pkg/kubectl/cmd/create/create_priorityclass_test.go
  pkg/kubectl/cmd/create/create_rolebinding_test.go
  pkg/kubectl/cmd/create/create_secret_test.go
  pkg/kubectl/cmd/create/create_serviceaccount_test.go
  pkg/kubectl/cmd/drain/drain_test.go
  pkg/kubectl/cmd/exec/exec_test.go
  pkg/kubectl/cmd/expose/expose_test.go
  pkg/kubectl/cmd/portforward/portforward_test.go
  pkg/kubectl/cmd/rollout/BUILD
  pkg/kubectl/cmd/rollout/rollout_pause_test.go
  pkg/kubectl/cmd/run/run_test.go
  pkg/kubectl/cmd/taint/taint_test.go
  pkg/kubectl/cmd/top/top_node_test.go
  pkg/kubectl/cmd/top/top_pod_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/watch_test.go
  staging/src/k8s.io/cli-runtime/pkg/resource/helper_test.go
  staging/src/k8s.io/client-go/BUILD
  staging/src/k8s.io/client-go/deprecated-dynamic/BUILD
  staging/src/k8s.io/client-go/deprecated-dynamic/client.go
  staging/src/k8s.io/client-go/deprecated-dynamic/client_pool.go
  staging/src/k8s.io/client-go/deprecated-dynamic/client_test.go
  staging/src/k8s.io/client-go/dynamic/BUILD
  staging/src/k8s.io/client-go/dynamic/client_test.go
  staging/src/k8s.io/client-go/dynamic/scheme.go
  staging/src/k8s.io/client-go/dynamic/simple.go
  staging/src/k8s.io/client-go/rest/client.go
  staging/src/k8s.io/client-go/rest/client_test.go
  staging/src/k8s.io/client-go/rest/config.go
  staging/src/k8s.io/client-go/rest/config_test.go
  staging/src/k8s.io/client-go/rest/fake/fake.go
  staging/src/k8s.io/client-go/rest/request.go
  staging/src/k8s.io/client-go/rest/request_test.go
  staging/src/k8s.io/client-go/util/flowcontrol/throttle.go
  staging/src/k8s.io/client-go/util/flowcontrol/throttle_test.go
  test/e2e/apimachinery/BUILD
  test/e2e/apimachinery/protocol.go
  test/e2e/network/BUILD
  test/e2e/network/service_latency.go
Labels: approved, lgtm, size/XXL

#954 Merge perftest back to master
  cmd/kubelet/app/BUILD
  cmd/kubelet/app/server.go
  hack/arktos-up.sh
  pkg/kubelet/kubelet.go
  pkg/registry/cachesize/cachesize.go
Labels: approved, lgtm, size/S

#958 switch to rp client for node
  pkg/kubelet/kubelet_node_status.go
Labels: approved, lgtm, size/XS

#957 Use insecure port in configs only for scaleout architecture
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
Labels: approved, lgtm, size/M

#931 1.18 improvement kubelet
  pkg/controller/vmpod/vm_controller.go
  pkg/kubelet/container/helpers.go
  pkg/kubelet/container/helpers_test.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/status/BUILD
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/util/pod/BUILD
  pkg/util/pod/pod.go
  pkg/util/pod/pod_test.go
  test/e2e/node/BUILD
  test/e2e/node/pods.go
Labels: approved, lgtm, size/L

#939 Use insecure-port only for scaleout, cleanup common.sh
  cluster/common.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/util.sh
Labels: approved, lgtm, size/L

#961 refactor to retire KubeClient in Kubelet
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_node_status_test.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
Labels: approved, lgtm, size/M

#964 Make perf scripts ready for insecure scale-out tests
  cluster/gce/config-default.sh
  cluster/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/M
