Repository CentaurusInfra/arktos, pull requests merged in 2021-11, with the labels that each got.

#1218 Rename tech doc name - CI bot complains
  docs/misc/Introduction_to_Google_Anthos.pptx
Labels: size/XS

#1114 Support for Mizar CNI in arktos-up
  build/lib/release.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/BUILD
  cluster/gce/gci/configure.sh
  cluster/gce/gci/proxy-configure-helper.sh
  cluster/gce/gci/proxyserver.yaml
  cluster/gce/gci/scaleoutserver-helper.sh
  cluster/gce/util.sh
  docs/misc/Introduction_to_Google_Anthos.pptx
  docs/setup-guide/arktos-with-mizar-cni.md
  hack/arktos-cni.rc
  hack/arktos-up.sh
  hack/lib/common-var-init.sh
  hack/testdata/default-mizar-network.tmpl
  test/kubemark/start-kubemark.sh
Labels: size/XL

#1220 kunsupported cgroup setup causes kubelet to emit a warning rather than existing
  cmd/kubelet/app/server.go
Labels: size/S, approved, lgtm

#1223 Mizar integration for arktos-up
  docs/setup-guide/arktos-with-mizar-cni.md
  hack/arktos-cni.rc
  hack/arktos-up.sh
  hack/lib/common-var-init.sh
  hack/testdata/mizar/deploy.mizar.next.yaml
Labels: size/XL

#1224 Daemonset controller supports multi resource partitions
  cmd/kube-controller-manager/app/apps.go
  hack/lib/common.sh
  pkg/controller/daemon/BUILD
  pkg/controller/daemon/daemon_controller.go
  pkg/controller/daemon/daemon_controller_test.go
  pkg/controller/daemon/update_test.go
  test/integration/daemonset/daemonset_test.go
Labels: size/M, lgtm

#1228 Add csr to rp controller
  cluster/gce/gci/configure-helper-common.sh
Labels: size/XS, approved, lgtm

#1225 Support multiple RPs in Mizar node controller
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-endpoints-controller.go
  pkg/controller/mizar/mizar-namespace-controller.go
  pkg/controller/mizar/mizar-network-policy-controller.go
  pkg/controller/mizar/mizar-node-controller.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-service-controller.go
  pkg/controller/mizar/mizar-starter-controller.go
  pkg/controller/mizar/mizar_node_controller_test.go
Labels: size/L, lgtm

#1227 kube-up.sh support scaleout
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/scaleoutserver-helper.sh
  cluster/gce/util.sh
  cluster/kube-down.sh
  cluster/kube-up.sh
  cluster/proxy-down.sh
  cluster/validate-cluster.sh
  test/kubemark/gce/util.sh
  test/kubemark/run-e2e-tests.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: size/XXL

#1226 openstack api support design doc
  docs/design-proposals/apiserver/openstack-api-support.md
Labels: size/L

#1231 [Arktos-Mizar-Integration] Design for arktos changes in 2022-01-30 release
  docs/design-proposals/multi-tenancy/multi-tenancy-network-mizar-integration.md
Labels: size/L

#1235 write config to stop running of mizar kopf when cluster is arktos
  hack/arktos-up.sh
Labels: size/XS, lgtm

#1234 Add node tags for rp minion vms
  cluster/gce/util.sh
Labels: size/XS, lgtm
