Repository CentaurusInfra/arktos, pull requests merged in 2021-03, with the labels that each got.

#1003 Scheduler talks to TPs directly with SSL enabled in dev environment
  cmd/kube-scheduler/app/config/config.go
  cmd/kube-scheduler/app/options/deprecated.go
  cmd/kube-scheduler/app/options/options.go
  cmd/kube-scheduler/app/server.go
  docs/setup-guide/scale-out-local-dev-setup.md
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  hack/lib/util.sh
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  staging/src/k8s.io/kube-scheduler/config/v1alpha1/types.go
  staging/src/k8s.io/kube-scheduler/config/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#1011 Use kubeconfig for TPs in nodelifecycle controller
  api/api-rules/violation_exceptions.list
  cmd/genutils/genutils.go
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/nodelifecyclecontroller.go
  cmd/kube-scheduler/app/options/BUILD
  cmd/kube-scheduler/app/options/options.go
  cmd/kubemark/BUILD
  cmd/kubemark/hollow-node.go
  docs/setup-guide/scale-out-local-dev-setup.md
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  hack/lib/util.sh
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/nodelifecycle/config/types.go
  pkg/controller/nodelifecycle/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/nodelifecycle/config/zz_generated.deepcopy.go
  pkg/controller/util/node/BUILD
  pkg/controller/util/node/controller_utils.go
  pkg/controller/util/node/controller_utils_test.go
  staging/src/k8s.io/client-go/BUILD
  staging/src/k8s.io/client-go/util/clientutil/BUILD
  staging/src/k8s.io/client-go/util/clientutil/clientutil.go
  staging/src/k8s.io/client-go/util/clientutil/clientutil_test.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
Labels: size/XL

#1014 scheduler uses all nodes from multiple RPs in one big pool
  pkg/scheduler/factory/factory.go
  pkg/scheduler/scheduler.go
Labels: size/S

#1015 Multiple RPs support in KCM
  cmd/cloud-controller-manager/app/config/BUILD
  cmd/cloud-controller-manager/app/config/config.go
  cmd/cloud-controller-manager/app/core.go
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/config/config.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/core.go
  cmd/kube-controller-manager/app/options/BUILD
  cmd/kube-controller-manager/app/options/options.go
  hack/lib/common.sh
  pkg/controller/cloud/node_controller.go
  pkg/controller/cloud/node_lifecycle_controller.go
  pkg/controller/service/BUILD
  pkg/controller/service/service_controller.go
  pkg/controller/volume/attachdetach/BUILD
  pkg/controller/volume/attachdetach/attach_detach_controller.go
  pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
  pkg/controller/volume/persistentvolume/BUILD
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/controller/volume/persistentvolume/pv_controller_base.go
  pkg/util/node/BUILD
  pkg/util/node/nodecache_utils.go
Labels: size/L

#1019 Enable profiling
  cluster/gce/gci/configure-helper-common.sh
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/controller-manager/app/options/debugging.go
  cmd/controller-manager/app/options/generic.go
  cmd/kube-scheduler/app/options/BUILD
  cmd/kube-scheduler/app/options/options.go
  cmd/kube-scheduler/app/options/options_test.go
  pkg/scheduler/apis/config/v1alpha1/defaults.go
  staging/src/k8s.io/component-base/config/v1alpha1/defaults.go
  staging/src/k8s.io/component-base/config/v1alpha1/types.go
  staging/src/k8s.io/component-base/config/v1alpha1/zz_generated.conversion.go
  staging/src/k8s.io/component-base/config/v1alpha1/zz_generated.deepcopy.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
  staging/src/k8s.io/kube-scheduler/config/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#1021 Use kubeconfig to replace TP api server endpoints in kubelet
  cmd/kubelet/app/BUILD
  cmd/kubelet/app/options/options.go
  cmd/kubelet/app/server.go
  docs/setup-guide/scale-out-local-dev-setup.md
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  pkg/controller/volume/attachdetach/attach_detach_controller.go
  pkg/scheduler/BUILD
  pkg/scheduler/eventhandlers.go
  pkg/scheduler/factory/factory.go
  pkg/scheduler/internal/cache/BUILD
  pkg/scheduler/internal/cache/debugger/BUILD
  pkg/util/node/BUILD
  staging/src/k8s.io/client-go/tools/cache/controller.go
Labels: lgtm, size/L

#1025 Fix pod GC issue in scale out case
  cmd/kube-controller-manager/app/core.go
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common-var-init.sh
  pkg/controller/podgc/gc_controller.go
Labels: size/L

#1028 Enable serviceaccount & serviceaccount-token controller in RP local cluster
  hack/lib/common.sh
Labels: lgtm, size/XS

#1027 Fix issue 1023
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
Labels: approved, lgtm, size/XS

#1029 Fix kube-proxy stop running issue in local scale up cluster
  hack/lib/common.sh
Labels: lgtm, size/XS

#1030 Pickup critical bugfix from master to 430 branch
  cluster/addons/rbac/kubelet-cert-rotation/kubelet-certificate-management.yaml
  cluster/addons/rbac/legacy-kubelet-user-disable/kubelet-binding.yaml
  cluster/addons/rbac/legacy-kubelet-user/kubelet-binding.yaml
  cluster/gce/addons/podsecuritypolicies/node-binding.yaml
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  pkg/kubelet/kubelet.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  test/kubemark/resources/start-kubemark-master.sh
Labels: size/S

#1026 Fix GC controller delete pod issue for multi-tenancy
  go.sum
  pkg/controller/podgc/gc_controller.go
  pkg/controller/podgc/gc_controller_test.go
Labels: approved, lgtm, size/M

#1031 fix kube controller command line args in 430 branch
  cluster/gce/gci/configure-helper-common.sh
  pkg/kubelet/kubelet.go
Labels: lgtm, size/S

#1022 Fix reference links in ControllerFramework.md
  docs/design-proposals/controller/scaleout-framework/ControllerFramework.md
Labels: approved, lgtm, size/XS

#1033 Add some log to perf-test tool.
  perf-tests/clusterloader2/cmd/clusterloader.go
  perf-tests/clusterloader2/pkg/util/multi-tenancy.go
Labels: lgtm, size/XS

#1034 Double GC/RS controller QPS. Guarded with feature gate.
  cmd/kube-controller-manager/app/apps.go
  cmd/kube-controller-manager/app/core.go
  hack/arktos-up-scale-out-poc.sh
  pkg/features/kube_features.go
  staging/src/k8s.io/code-generator/_examples/apiserver/openapi/BUILD
  staging/src/k8s.io/sample-apiserver/pkg/generated/openapi/BUILD
Labels: lgtm, size/M

#1032 perftest tool: bypass accessing RPs
  perf-tests/clusterloader2/cmd/clusterloader.go
  perf-tests/clusterloader2/pkg/config/cluster.go
Labels: lgtm, size/S

#1037 Double GC/RS controller QPS. Guarded with feature gate.
  cmd/kube-controller-manager/app/apps.go
  cmd/kube-controller-manager/app/core.go
  hack/arktos-up.sh
  pkg/features/kube_features.go
Labels: approved, lgtm, size/M

#1035 support multiple RP - 1: kubemark structure update to support multiple RPs
  test/kubemark/gce/util.sh
  test/kubemark/resources/hollow-node_template_scaleout.yaml
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: size/L

#1041 multiple RP support -2: reset controller for multiple RPs
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-scheduler/app/options/options.go
  test/kubemark/start-kubemark.sh
Labels: lgtm, size/L

#1044 bug fix: static pods are constantly recycled
  pkg/controller/podgc/gc_controller.go
Labels: bug, size/M

#1050 Disable Daemonset from perf-test: load testing
  perf-tests/clusterloader2/testing/experiments/enable_daemonset.yaml
  perf-tests/clusterloader2/testing/load/config.yaml
Labels: approved, lgtm, size/S

#1060 bug fix 1048: api server tsl handshake error with proxy server (#1051)
  cmd/haproxy-cfg-generator/cfg_generator.go
  cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
Labels: approved, lgtm, size/M

#1063 scheduler binder searches node from all RPs
  pkg/controller/volume/scheduling/scheduler_binder.go
Labels: lgtm, size/S
