Repository CentaurusInfra/arktos, pull requests merged in 2021-08, with the labels that each got.

#1131 bug fix: gc controller deletes pods as it cannot access node resources
  cmd/kube-controller-manager/app/controllermanager.go
Labels: lgtm, size/XS

#1133 Start informer after index was added
  cmd/kube-controller-manager/app/core.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/util/node/controller_utils.go
  test/integration/scheduler/taint_test.go
Labels: size/M, lgtm

#1134 PR 96117 - Disable watchcache for events 1.18
  pkg/registry/cachesize/cachesize.go
Labels: size/XS, lgtm

#1129 Use watch instead of list pods in node controller
  cmd/kube-controller-manager/app/core.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/BUILD
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/util/node/controller_utils.go
  test/integration/scheduler/taint_test.go
Labels: area/scalability, size/L, approved, lgtm

#1136 Set watch never expire
  staging/src/k8s.io/client-go/tools/cache/reflector.go
  staging/src/k8s.io/client-go/tools/cache/shared_informer.go
Labels: size/XS, lgtm

#1147 Merge master PR 1129 (replace watch with list pods in node controller) - pick up UT changes.
  pkg/controller/nodelifecycle/scheduler/BUILD
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
Labels: size/L

#1148 Revert changes to resyncCheckPeriod. It is not used in watch time out.
  staging/src/k8s.io/client-go/tools/cache/shared_informer.go
Labels: size/XS

#1149 Increase watch timeout period. Trying to reduce impact on frequently …
  staging/src/k8s.io/client-go/tools/cache/reflector.go
Labels: size/XS

#1150 Reduce kubelet getting node requests.
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_node_status.go
Labels: size/S

#1151 porting changes from community issue 77733
  pkg/controller/nodelifecycle/BUILD
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/nodelifecycle/scheduler/taint_manager.go
  pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
  pkg/controller/util/node/BUILD
  pkg/controller/util/node/controller_utils.go
Labels: size/XXL, lgtm

#1158 add POD_STARTUP_LATENCY_THRESHOLD override for 25K_nodes
  perf-tests/clusterloader2/testing/density/25k_nodes/override.yaml
  perf-tests/clusterloader2/testing/density/config.yaml
Labels: size/XS, approved, lgtm

#1159 Add option to skip deleting latency pods or saturationn pods
  perf-tests/clusterloader2/testing/density/config.yaml
  perf-tests/clusterloader2/testing/experiments/deleting_latency_pods.yaml
  perf-tests/clusterloader2/testing/experiments/deleting_saturation_pods.yaml
Labels: size/XS, approved, lgtm

#1163 Reduce perf test list all pods from API server cache
  perf-tests/clusterloader2/pkg/measurement/common/scheduling_throughput.go
  perf-tests/clusterloader2/pkg/measurement/util/object_store.go
  perf-tests/clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: size/L, lgtm

#1164 Add "create_to_run" to pod latency
  perf-tests/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  test/e2e/framework/perf_util.go
Labels: size/XS, lgtm
