Repository CentaurusInfra/arktos, pull requests merged in 2021-02, with the labels that each got.

#969 fix issue that causes wrong service tier in scale-out
  cluster/gce/util.sh
Labels: Verifying, approved, lgtm, size/XS

#971 Secure client--proxy API for scaleout, and remove generation of unnecessary kubeconfig files
  cluster/common.sh
  cluster/gce/util.sh
  hack/scale_out_poc/config_haproxy/haproxy.cfg.template
  test/kubemark/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/L

#959 Add the design doc for the scale out architecture
  docs/design-proposals/arch/arktos_scale_out.md
  docs/design-proposals/arch/images/scaleout_architecture.png
  docs/design-proposals/arch/images/scaleout_component.png
  docs/design-proposals/arch/images/scaleout_deployment.png
Labels: approved, lgtm, size/L

#966 fix volume usage for kube clients
  cmd/kubelet/app/server.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_node_status_test.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod_actions.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/volume_host.go
  pkg/kubelet/volumemanager/volume_manager.go
  pkg/kubemark/hollow_kubelet.go
  pkg/volume/util/operationexecutor/BUILD
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, size/L

#935 1.18 improvement kcm metadataclient
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/core.go
  hack/.golint_failures
  hack/arktos_copyright_copied_k8s_files
  hack/arktos_copyright_copied_modified_k8s_files
  pkg/controller/.import-restrictions
  pkg/controller/garbagecollector/BUILD
  pkg/controller/garbagecollector/garbagecollector.go
  pkg/controller/garbagecollector/garbagecollector_test.go
  pkg/controller/garbagecollector/graph_builder.go
  pkg/controller/garbagecollector/operations.go
  pkg/controller/garbagecollector/patch.go
  pkg/controller/namespace/BUILD
  pkg/controller/namespace/deletion/BUILD
  pkg/controller/namespace/deletion/namespaced_resources_deleter.go
  pkg/controller/namespace/deletion/namespaced_resources_deleter_test.go
  pkg/controller/namespace/namespace_controller.go
  staging/src/k8s.io/client-go/BUILD
  staging/src/k8s.io/client-go/metadata/BUILD
  staging/src/k8s.io/client-go/metadata/fake/BUILD
  staging/src/k8s.io/client-go/metadata/fake/simple.go
  staging/src/k8s.io/client-go/metadata/fake/simple_test.go
  staging/src/k8s.io/client-go/metadata/interface.go
  staging/src/k8s.io/client-go/metadata/metadata.go
  staging/src/k8s.io/client-go/metadata/metadata_test.go
  staging/src/k8s.io/client-go/metadata/metadatainformer/BUILD
  staging/src/k8s.io/client-go/metadata/metadatainformer/informer.go
  staging/src/k8s.io/client-go/metadata/metadatainformer/informer_test.go
  staging/src/k8s.io/client-go/metadata/metadatainformer/interface.go
  staging/src/k8s.io/client-go/metadata/metadatalister/BUILD
  staging/src/k8s.io/client-go/metadata/metadatalister/interface.go
  staging/src/k8s.io/client-go/metadata/metadatalister/lister.go
  staging/src/k8s.io/client-go/metadata/metadatalister/lister_test.go
  staging/src/k8s.io/client-go/metadata/metadatalister/shim.go
  staging/src/k8s.io/client-go/testing/fixture.go
  test/e2e_node/services/BUILD
  test/e2e_node/services/namespace_controller.go
  test/integration/apiserver/BUILD
  test/integration/apiserver/apiserver_test.go
  test/integration/garbagecollector/BUILD
  test/integration/garbagecollector/garbage_collector_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#976 Fix priorityclass missing in loadtest
  perf-tests/clusterloader2/pkg/framework/BUILD
  perf-tests/clusterloader2/pkg/framework/framework.go
  perf-tests/clusterloader2/pkg/framework/multiclient.go
Labels: approved, lgtm, size/M

#977 add a switch to disable PV in load test
  perf-tests/clusterloader2/testing/experiments/disable_pvs.yaml
  perf-tests/clusterloader2/testing/load/deployment.yaml
Labels: approved, lgtm, size/XS

#983 Add the change log for v0.7 release.
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/README.md
Labels: approved, lgtm, size/S

#984 Show more detailed message for file-updated-check
  hack/make-rules/update.sh
Labels: approved, lgtm, size/XS

#979 Fix GCE deployment and arktos-up to correctly enable Vertical Scaling feature
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  hack/arktos-up.sh
  hack/lib/common-var-init.sh
Labels: approved, lgtm, size/S

#985 Read Arktos version from file instead of environment variable
  hack/lib/version.sh
  pkg/version/VERSION.sh
Labels: approved, lgtm, size/S

#986 Use secure communication for client <--> proxy communication, cleanup unnecessary config files
  cluster/common.sh
  cluster/gce/util.sh
  cmd/haproxy-cfg-generator/data/haproxy.cfg.template
  cmd/haproxy-cfg-generator/data/sample_four_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_one_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_three_tp_haproxy.cfg
  cmd/haproxy-cfg-generator/data/sample_two_tp_haproxy.cfg
  test/kubemark/gce/util.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, lgtm, size/L

#987 Use HTTPS as etcd-apiserver protocol when mTLS is enabled
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/manifests/etcd.manifest
  go.mod
Labels: approved, lgtm, size/M

#989 Consistent etcd key path
  hack/lib/common.sh
  pkg/api/testapi/testapi_test.go
  pkg/apis/core/types.go
  pkg/cloudfabric-controller/deployment/deployment_controller_test.go
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/util/node/controller_utils.go
  pkg/kubectl/cmd/drain/drain_test.go
  pkg/kubectl/drain/drain.go
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/apimachinery/pkg/api/validation/generic.go
  staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/tenantinfo.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/tenantinfo_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo_test.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
  staging/src/k8s.io/cli-runtime/pkg/resource/builder.go
  staging/src/k8s.io/client-go/dynamic/fake/simple.go
  staging/src/k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go
  staging/src/k8s.io/client-go/testing/fixture.go
  staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
  test/e2e/arktos/multi_tenancy/test_suites/tenant_init_delete_test.yaml
  test/integration/auth/rbac_test.go
  test/integration/etcd/data.go
  test/integration/master/transformation_testcase.go
Labels: approved, lgtm, size/XL

#992 fix issue 655
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go
  test/e2e/arktos/multi_tenancy/test_suites/crd/test_system_share_crd.yaml
Labels: approved, lgtm, size/XS

#990 add hack/arktos_cherrypick.sh
  hack/arktos_cherrypick.sh
Labels: approved, lgtm, size/L

#994 Scale-out set up for local dev environment + quick manual
  cmd/kubelet/app/options/options.go
  docs/setup-guide/scale-out-local-dev-setup.md
  hack/arktos-up-scale-out-poc.sh
  hack/lib/common.sh
  hack/lib/util.sh
Labels: size/XL

#996 fix kubelet permission issue in kube-up
  cluster/addons/rbac/kubelet-cert-rotation/kubelet-certificate-management.yaml
  cluster/addons/rbac/legacy-kubelet-user-disable/kubelet-binding.yaml
  cluster/addons/rbac/legacy-kubelet-user/kubelet-binding.yaml
  cluster/gce/addons/podsecuritypolicies/node-binding.yaml
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
  pkg/kubelet/kubelet.go
  test/kubemark/resources/start-kubemark-master.sh
Labels: approved, lgtm, size/S

#991 Scheduler to connect to RP directly via separated client
  cluster/gce/gci/configure-helper-common.sh
  cmd/kube-scheduler/app/config/config.go
  cmd/kube-scheduler/app/options/deprecated.go
  cmd/kube-scheduler/app/options/options.go
  cmd/kube-scheduler/app/server.go
  pkg/scheduler/apis/config/types.go
  pkg/scheduler/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/scheduler/apis/config/zz_generated.deepcopy.go
  staging/src/k8s.io/kube-scheduler/config/v1alpha1/types.go
  staging/src/k8s.io/kube-scheduler/config/v1alpha1/zz_generated.deepcopy.go
  test/kubemark/start-kubemark.sh
Labels: approved, lgtm, size/L
