Repository CentaurusInfra/arktos, pull requests merged in 2022-01, with the labels that each got.

#1259 Bug fix for scale out local dev env: set FIRST_SERVICE_CLUSTER_IP from TENANT_PARTITION_SERVICE_SUBNET
  hack/arktos-up-scale-out-poc.sh
Labels: size/XS

#1263 in arktos-up-scale-out-poc.sh, write config to stop running of mizar kopf when cluster is arktos
  hack/arktos-up-scale-out-poc.sh
Labels: size/XS, lgtm

#1261 Bug fix for scale out local dev env: set FIRST_SERVICE_CLUSTER_IP from TENANT_PARTITION_SERVICE_SUBNET
  hack/arktos-up-scale-out-poc.sh
Labels: size/XS

#1260 reboot, snapshot, retsore action and handler redirect
  pkg/registry/core/pod/storage/storage.go
  staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/response.go
  staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/BUILD
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  test/e2e/arktos/createImage.json
  test/e2e/arktos/reboot.json
  test/e2e/arktos/rebuild.json
Labels: size/L

#1266 openstack essential flavors and images support for VM creations -- part 1
  staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackRequestTemplate.json
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  test/e2e/arktos/testvm.json
Labels: size/L

#1244 kubelet gets resources from API server of pod origin
  docs/design-proposals/arch/daemonset.md
  pkg/controller/volume/attachdetach/attach_detach_controller.go
  pkg/controller/volume/expand/expand_controller.go
  pkg/controller/volume/persistentvolume/volume_host.go
  pkg/kubelet/config/config.go
  pkg/kubelet/configmap/BUILD
  pkg/kubelet/configmap/configmap_manager.go
  pkg/kubelet/configmap/configmap_manager_test.go
  pkg/kubelet/configmap/fake_manager.go
  pkg/kubelet/kubeclientmanager/BUILD
  pkg/kubelet/kubeclientmanager/kubeclient_manager.go
  pkg/kubelet/kubeclientmanager/kubeclient_manager_test.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/pod_actions.go
  pkg/kubelet/secret/BUILD
  pkg/kubelet/secret/fake_manager.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/secret/secret_manager_test.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/token/BUILD
  pkg/kubelet/token/token_manager.go
  pkg/kubelet/token/token_manager_test.go
  pkg/kubelet/util/manager/BUILD
  pkg/kubelet/util/manager/cache_based_manager.go
  pkg/kubelet/util/manager/cache_based_manager_test.go
  pkg/kubelet/util/manager/manager.go
  pkg/kubelet/util/manager/watch_based_manager.go
  pkg/kubelet/util/manager/watch_based_manager_test.go
  pkg/kubelet/volume_host.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/volume_manager_test.go
  pkg/volume/configmap/configmap.go
  pkg/volume/plugins.go
  pkg/volume/projected/projected.go
  pkg/volume/secret/secret.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_generator.go
  test/integration/kubelet/watch_manager_test.go
Labels: size/XL, approved, lgtm

#1265 Support adding workers for multiple TPs.
  hack/arktos-worker-up.sh
Labels: size/S, lgtm

#1252 SystemDaemonSet admission plugin allows daemonset created in system tenant only
  pkg/kubeapiserver/options/BUILD
  pkg/kubeapiserver/options/plugins.go
  plugin/BUILD
  plugin/pkg/admission/systemdaemonset/BUILD
  plugin/pkg/admission/systemdaemonset/admission.go
  plugin/pkg/admission/systemdaemonset/admission_test.go
  test/integration/etcd/multi_tenancy_etcd_cross_group_test.go
  test/integration/etcd/multi_tenancy_etcd_storage_path_test.go
Labels: size/L, approved, lgtm

#1267 openstack essential flavors and images support for VM creations -- part2
  staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
Labels: size/M, lgtm

#1264 add Ubuntu support for kube-up.sh
  cluster/addons/dns/coredns/coredns.yaml.base
  cluster/addons/dns/coredns/coredns.yaml.in
  cluster/addons/dns/coredns/coredns.yaml.sed
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/scaleoutserver-helper.sh
  cmd/kubeadm/app/phases/addons/dns/manifests.go
Labels: size/M

#1271 kube-up.sh support Daemonset for scale-out
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/util.sh
Labels: size/S

#1273 Change kube-up.sh to use Containerd as default runtime
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure.sh
  cluster/gce/util.sh
Labels: size/L

#1281 [Mizar-Arktos-Integration]Tenant-vpc-support: finalize code changes for mizar pod controller and mizar arktos network controller after successful integration tests
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/mizarcontrollers.go
  cmd/kubeadm/app/phases/addons/dns/manifests.go
  hack/lib/protoc-mizar.sh
  hack/runtime/default_mizar_network_subnet_template.json
  hack/runtime/default_mizar_network_vpc_template.json
  hack/update-generated-mizar.sh
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/builtins.pb.go
  pkg/controller/mizar/builtins.proto
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/util.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
  staging/src/k8s.io/apiserver/pkg/server/routes/BUILD
Labels: size/XL

#1282 register network crd only for kube-up, not for kubemark
  cluster/gce/util.sh
Labels: size/S, lgtm

#1241 Mizar-Arktos kube-up for scaleup architecture
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/util.sh
Labels: size/L, lgtm

#1284 batch creation and list vm support
  staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackBatchRequestTemplate.json
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
  test/e2e/arktos/testvm-batch.json
  test/e2e/arktos/testvm-list.json
  test/e2e/arktos/testvm.json
Labels: size/L, lgtm

#1291 Tenant controller logic - only call create network when necessary
  cmd/kube-controller-manager/app/core.go
  pkg/controller/tenant/BUILD
  pkg/controller/tenant/tenant_controller.go
  pkg/controller/tenant/tenant_controller_test.go
  test/integration/tenantcontroller/BUILD
  test/integration/tenantcontroller/tenantcontroller_test.go
Labels: size/M, approved, lgtm

#1294 Share same networkInformerFactory in mizar controllers
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-service-controller.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
Labels: size/L, lgtm

#1295 Bug fix: add pod creation event back to queue when network is not ready
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-service-controller.go
Labels: size/S

#1299 Remove json templates in constructing Openstack request
  staging/src/k8s.io/apiserver/pkg/util/openstack/BUILD
  staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackBatchRequestTemplate.json
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackRequestTemplate.json
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types_test.go
Labels: size/L

#1296 Assign pod to default mizar network only when Mizar VPC/subnet annotation is not present in pod
  pkg/controller/mizar/mizar-pod-controller.go
Labels: size/M

#1304 Start proxy in worker
  hack/arktos-worker-up.sh
Labels: size/M, lgtm

#1306 Grant necessary permission to mizar service controller
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
Labels: size/XS

#1308 Slight refactor and essential UT
  staging/src/k8s.io/apiserver/pkg/util/openstack/BUILD
  staging/src/k8s.io/apiserver/pkg/util/openstack/flavors.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/images.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types_test.go
Labels: size/XL

#1312 In get or create service function, get needs to happen before create.
  cmd/arktos-network-controller/app/wellknown_service.go
Labels: size/S

#1310 [kube-up][scale-out]Automatically create default network object (flat or mizar) of for system tenant
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/master-helper.sh
  cluster/gce/gci/scaleoutserver-helper.sh
  cluster/gce/manifests/kube-controller-manager.manifest
  cluster/gce/util.sh
Labels: size/L, lgtm

#1298 Start arktos-network-controller for kube-up
  build/BUILD
  build/common.sh
  build/debian-hyperkube-base/Dockerfile
  build/debs/BUILD
  build/lib/release.sh
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/manifests/arktos-network-controller.manifest
  cluster/gce/util.sh
  cmd/BUILD
  hack/lib/golang.sh
Labels: size/L, lgtm

#1314 ServerType update to fit Openstack required and key optional configs.
  pkg/controller/mizar/mizar-pod-controller.go
  staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/openstackutils_test.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types_test.go
  test/e2e/arktos/testvm.json
Labels: size/L, lgtm
