Repository CentaurusInfra/arktos, pull requests merged in 2022-02, with the labels that each got.

#1321 Filter Openstack request related VMs in list and basic error handling
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  staging/src/k8s.io/apiserver/pkg/server/routes/openstack.go
  staging/src/k8s.io/apiserver/pkg/util/openstack/types.go
  test/e2e/arktos/testvm-batch.json
Labels: size/S, lgtm

#1323 Wait mizar ready when starting up local cluster
  hack/arktos-up-scale-out-poc.sh
  hack/arktos-up.sh
  hack/lib/common.sh
Labels: size/M

#1319 arktos network controller arg --resource-name-salt set valid value in kube-up scale-out cluster
  cluster/gce/gci/configure-helper.sh
Labels: size/XS, lgtm

#1313 In get or create service function, get needs to happen before create.
  cmd/arktos-network-controller/app/controller_test.go
  cmd/arktos-network-controller/app/wellknown_service.go
Labels: size/S, approved, lgtm

#1331 kube-up.sh not use DISABLE_ADMISSION_PLUGINS env var
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
Labels: size/S, lgtm

#1327 [kube-up][scale-out]Automatically create default mizar vpc and subnet for tenants
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/master-helper.sh
  cluster/gce/gci/scaleoutserver-helper.sh
  cluster/gce/manifests/kube-controller-manager.manifest
  cluster/gce/util.sh
  cmd/BUILD
  cmd/kube-controller-manager/app/mizarcontrollers.go
Labels: size/L, lgtm

#1342 Use builtin json struct instead of template files for Mizar VPC
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/master-helper.sh
  cluster/gce/gci/scaleoutserver-helper.sh
  cluster/gce/manifests/kube-controller-manager.manifest
  cluster/gce/util.sh
  cmd/BUILD
  cmd/kube-controller-manager/app/mizarcontrollers.go
  hack/runtime/default_mizar_network_subnet_template.json
  hack/runtime/default_mizar_network_vpc_template.json
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
  pkg/controller/mizar/types.go
  pkg/controller/mizar/util.go
Labels: size/XL

#1344 Simplify and refactor createUnstructuredObject for CRD object creation
  cmd/BUILD
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/BUILD
  pkg/controller/controller_utils.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
  pkg/controller/mizar/types.go
Labels: size/L

#1341 openstack api support doc
  docs/design-proposals/apiserver/openstack-api-support.md
Labels: size/XL, approved, lgtm

#1343 kube-up kubelet uses real DNS upstream server for systemd-enabled Ubuntu
  cluster/gce/gci/configure-helper-common.sh
Labels: size/S, lgtm

#1349 Annotation service with default vpc/subnet for mizar integration
  pkg/controller/mizar/builtins.pb.go
  pkg/controller/mizar/builtins.proto
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-service-controller.go
Labels: size/L

#1351 kube-proxy of rp nodes connecting to tp masters
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/manifests/kube-proxy.manifest
Labels: size/S, lgtm

#1320 Mizar-Arktos integration with multitenancy network isolation for n-TP x n-RP scale out architecture
  build/lib/release.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  third_party/mizar/mizar-crds.yaml
  third_party/mizar/mizar-daemon.yaml
  third_party/mizar/mizar-operator.yaml
Labels: size/XL

#1352 Mizar service controller code simplify and logic fix
  pkg/controller/mizar/mizar-service-controller.go
Labels: size/L, lgtm

#1362 Make local scale out have same architecture as kube up
  hack/arktos-up-scale-out-poc.sh
Labels: size/M

#1332 kube-up.sh support scaleout
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/gci/scaleoutserver-helper.sh
  cluster/gce/util.sh
  cluster/kube-down.sh
  cluster/kube-up.sh
  cluster/proxy-down.sh
  cluster/validate-cluster.sh
  test/kubemark/gce/util.sh
  test/kubemark/run-e2e-tests.sh
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: size/XXL, approved, lgtm

#1363 fix issue #1361
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
Labels: size/M

#1367 Add TP master into mizar droplets
  cmd/kube-controller-manager/app/mizarcontrollers.go
  hack/arktos-up-scale-out-poc.sh
  pkg/controller/mizar/mizar-node-controller.go
  third_party/mizar/mizar-daemon-tpmaster.yaml
Labels: size/L, lgtm

#1365 [Arktos-Mizar-Integration][ScaleOut]For starting mizar-operator pod on scale-out TP servers successfully
  hack/arktos-up-scale-out-poc.sh
Labels: size/XS, lgtm

#1368 kube-up: start mizar daemon on tp master
  cluster/gce/util.sh
Labels: size/S, lgtm

#1370 minor: arktos network controller log messge change
  cmd/arktos-network-controller/app/controller.go
  cmd/arktos-network-controller/app/wellknown_service.go
Labels: size/S, approved, lgtm

#1375 fix kubectl missing error for scale-out
  cluster/gce/util.sh
Labels: size/M, lgtm

#1376 update golang version in setup-dev-env.md
  docs/setup-guide/setup-dev-env.md
  hack/setup-dev-node.sh
Labels: size/XS, approved, lgtm

#1371 Mizar VPC support for service, add TP master to mizar droplets
  cmd/kube-controller-manager/app/mizarcontrollers.go
  pkg/controller/mizar/builtins.pb.go
  pkg/controller/mizar/builtins.proto
  pkg/controller/mizar/mizar-node-controller.go
  pkg/controller/mizar/mizar-pod-controller.go
  pkg/controller/mizar/mizar-service-controller.go
  pkg/controller/mizar/mizar_node_controller_test.go
Labels: size/L, approved, lgtm

#1381 mizar preliminary installation not to install binary
  cluster/gce/gci/configure.sh
Labels: size/S, lgtm
