Repository CentaurusInfra/arktos, pull requests merged in 2022-03, with the labels that each got.

#1385 Kubeup scaleout mizar support
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/manifests/kube-proxy.manifest
  cluster/gce/util.sh
  third_party/mizar/mizar-crds.yaml
  third_party/mizar/mizar-daemon-tpmaster.yaml
  third_party/mizar/mizar-daemon.yaml
  third_party/mizar/mizar-operator.yaml
Labels: size/XL, approved, lgtm

#1389 Remove kube-dns from local env.
  hack/arktos-up-scale-out-poc.sh
Labels: size/XS

#1347 Design doc for Mizar-Arktos Integration
  docs/design-proposals/multi-tenancy/multi-tenancy-network-mizar-integration.md
Labels: size/L, approved, lgtm

#1392 VPC start ip range fix: only generate ip start from range [11, 19]U[21, 99]
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
Labels: size/S

#1393 static pods on different nodes get unique uids
  pkg/kubelet/config/common.go
Labels: size/XS, approved, lgtm

#1394 (backport to POC) static pods on different nodes are assigned unique uid
  pkg/kubelet/config/common.go
Labels: size/XS

#1395 VPC start ip range fix: only generate ip start from range [11, 19]U[21,99]
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
Labels: size/XS

#1396 Distinct VPC range, passing VPC start/end from cmd arg for scale out
  api/api-rules/violation_exceptions.list
  cmd/kube-controller-manager/app/mizarcontrollers.go
  cmd/kube-controller-manager/app/options/BUILD
  cmd/kube-controller-manager/app/options/mizararktosnetworkcontroller.go
  cmd/kube-controller-manager/app/options/options.go
  hack/arktos-up-scale-out-poc.sh
  hack/arktos-up.sh
  hack/lib/common-var-init.sh
  hack/lib/common.sh
  pkg/controller/apis/config/BUILD
  pkg/controller/apis/config/types.go
  pkg/controller/apis/config/v1alpha1/BUILD
  pkg/controller/apis/config/v1alpha1/defaults.go
  pkg/controller/apis/config/v1alpha1/doc.go
  pkg/controller/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/config/BUILD
  pkg/controller/mizar/config/doc.go
  pkg/controller/mizar/config/types.go
  pkg/controller/mizar/config/v1alpha1/BUILD
  pkg/controller/mizar/config/v1alpha1/conversion.go
  pkg/controller/mizar/config/v1alpha1/defaults.go
  pkg/controller/mizar/config/v1alpha1/doc.go
  pkg/controller/mizar/config/v1alpha1/register.go
  pkg/controller/mizar/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/mizar/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/mizar/config/zz_generated.deepcopy.go
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
  pkg/controller/mizar/mizar-service-controller.go
  pkg/controller/mizar/mizar_node_controller_test.go
  pkg/features/kube_features.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
Labels: size/XL

#1382 [Arktos] The scripts for scale-up + workers environment on AWS Ubuntu1804&Ubuntu2004 and scale-out 2x2 + workers environment on AWS Ubuntu 2004
  hack/arktos-cni.rc
  hack/arktos-up-scale-out-poc.sh
  hack/arktos-up.sh
  hack/arktos-worker-up.sh
  hack/lib/common-var-init.sh
  hack/lib/common.sh
Labels: size/L, approved, lgtm

#1397 kube-up support vpc range
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper-common.sh
  cluster/gce/util.sh
Labels: size/M, lgtm

#1402 Bug fix for populateCache - unstructured data cannot be unmarshalled …
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
Labels: size/L, lgtm

#1398 Distinct VPC range, passing VPC start/end from cmd arg for scale out
  api/api-rules/violation_exceptions.list
  cmd/kube-controller-manager/app/mizarcontrollers.go
  cmd/kube-controller-manager/app/options/BUILD
  cmd/kube-controller-manager/app/options/mizararktosnetworkcontroller.go
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-controller-manager/app/options/options_test.go
  hack/arktos-up-scale-out-poc.sh
  hack/arktos-up.sh
  hack/lib/common-var-init.sh
  hack/lib/common.sh
  pkg/controller/apis/config/BUILD
  pkg/controller/apis/config/types.go
  pkg/controller/apis/config/v1alpha1/BUILD
  pkg/controller/apis/config/v1alpha1/defaults.go
  pkg/controller/apis/config/v1alpha1/doc.go
  pkg/controller/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/apis/config/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/controller/mizar/BUILD
  pkg/controller/mizar/config/BUILD
  pkg/controller/mizar/config/doc.go
  pkg/controller/mizar/config/types.go
  pkg/controller/mizar/config/v1alpha1/BUILD
  pkg/controller/mizar/config/v1alpha1/conversion.go
  pkg/controller/mizar/config/v1alpha1/defaults.go
  pkg/controller/mizar/config/v1alpha1/doc.go
  pkg/controller/mizar/config/v1alpha1/register.go
  pkg/controller/mizar/config/v1alpha1/zz_generated.conversion.go
  pkg/controller/mizar/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/mizar/config/zz_generated.deepcopy.go
  pkg/controller/mizar/mizar-arktos-network-controller.go
  pkg/controller/mizar/mizar-arktos-network-controller_test.go
  pkg/controller/mizar/mizar-service-controller.go
  pkg/features/kube_features.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/types.go
  staging/src/k8s.io/kube-controller-manager/config/v1alpha1/zz_generated.deepcopy.go
Labels: size/XL, approved, lgtm

#1405 kube-up to add different service-cluster-ip-range for different TP
  cluster/gce/config-common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/util.sh
Labels: size/S, approved, lgtm

#1408 Update local dev environment setup manual for Mizar integration.
  README.md
  docs/README.md
  docs/setup-guide/multi-node-dev-cluster.md
  docs/setup-guide/scale-out-kube-up.md
  docs/setup-guide/scale-out-local-dev-setup.md
Labels: size/L, approved, lgtm
